### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lordcodes** [jneen/rouge#1006]
Can we prepare a release to use all the changes since the last one?

@dblessing - Is there anything I can do to help prepare it?

**Comment by dblessing** [comment]
@lordcodes Already working on it. Will be by end of day today.

**Comment by lordcodes** [comment]
@dblessing Thank you very much, sorry for asking, should have been more patient.

Looks great!

**Comment by dblessing** [comment]
No worries @lordcodes You couldn't have known. Glad to have this release out. Thanks for your contributions.
