### ISSUE TITLE
Add support for Robot Framework

### ISSUE THREAD

**Issue by bartkl** [jneen/rouge#1018]
It would be nice to add support for syntax highlighting of the [Robot Framework](http://robotframework.org/) language. Maybe I could look into adding this myself.

**Comment by michele-carignani** [comment]
+1

Maybe this other projects may serve as starting point?
* https://github.com/vkosuri/gedit-robot/blob/master/robot.lang
* https://github.com/vkosuri/npp-robot

**Comment by bartkl** [comment]
@michele-carignani Thanks, that might certainly help! Hope to make some time for this soon.

**Comment by michele-carignani** [comment]
Hi @bartkl , 

FYI after posting I noticed the PR https://github.com/jneen/rouge/pull/611 which is already in good status.

**Comment by bartkl** [comment]
Good catch, I'll close this issue then.

Thanks, that saves me a lot of effort that someone already did ;).
