### ISSUE TITLE
Maintenance of the project

### ISSUE THREAD

**Issue by metthal** [jneen/rouge#1095]
Hi. There has already been discussion about maintenance of this project last year (#890). Since then, there was still some activity but the last merged PR is from October. @vidarh did an amazing job reviewing PRs so it would be really cool if all of his work wouldn't be for nothing.

If I knew Ruby I would even volunteer for merging PRs myself but right now all I can do is start a discussion about this topic and hopefully it'll get us somewhere.

**Comment by dblessing** [comment]
I've been in communication with @vidarh. It's my intention to review their work and eventually promote them to maintainer. Please appreciate that maintainers have lots going on in their regular work and in life. It's not my intention to abandon this project or to leave people hanging. I'll get to it when I'm able.

**Comment by metthal** [comment]
Sorry if I sounded too harsh, English is not my first language so I might have chosen poor words to express myself. I completely understand that maintaining open-source project in a free time after work is not an easy task and I do appreciate all the work that has been put into this project so far.

And also thank you for your answer.
