### ISSUE TITLE
Add Twig Lexer?

### ISSUE THREAD

**Issue by daviddarnes** [jneen/rouge#188]
Not sure if the twig template language is as popular as liquid or handlebars, but I'd certainly like it to be added :smile:.

It's already in the [main pygments repo](https://bitbucket.org/birkenfeld/pygments-main/issue/927/missing-lexer-for-twig-language).

Thank you!

**Comment by tolry** [comment]
:+1: for twig/jinja Support

Gitlab is using rouge since 7.14 and therefore does no longer highlight jinja/twig templates correctly.

**Comment by jxn** [comment]
:+1: for what it's worth.  We use a lot of twig and jinja2.

**Comment by razorness** [comment]
:+1: The very famous PHP framework Symfony2 is using Twig by default. Primary, it's very similar to Django. So get it work! ;-)

**Comment by jneen** [comment]
Please keep in mind I do not get paid to work on rouge.

**Comment by daviddarnes** [comment]
@jneen fully aware! People are welcome to make a pull request for it!

**Comment by sousacleverti** [comment]
:+1:
