### ISSUE TITLE
Lexers should have human readable names

### ISSUE THREAD

**Issue by edwardloveall** [jneen/rouge#206]
I think it would be a good idea to have human readable names attached to each lexer. Some languages are easy to make by capitalizing the first letter (Ruby, Go, Swift, C) but it gets a little more complex with mid-word capitalization (JavaScript, XML, TeX) and even more difficult when symbols get involved (C++, Objective-C, C#).

My reasoning for this would be when a list of supported languages is available to the user, or when the detected language is displayed. These could likely be put in the lexers themselves along with the tag and file extensions.

**Comment by mpeteuil** [comment]
Looks like this is closable as a result of the work that was merged in with https://github.com/jneen/rouge/commit/d627db73fbadfbd6b75a38f28efd57eabbfb761a

**Comment by edwardloveall** [comment]
Thanks for lookin out!

**Comment by mpeteuil** [comment]
Sure thing, thanks for creating the `title` :smile:
