### ISSUE TITLE
Compatibility with Pygments Stylesheets

### ISSUE THREAD

**Issue by parkr** [jneen/rouge#230]
Is there a compat switch where we can continue to use Pygments stylesheets? I noticed that, with bash for example, `$` is given class `gp` by Rouge and class `nv` by Pygments. Any way to reconcile this?

**Comment by jneen** [comment]
You should be able to continue to use Pygments stylesheets.  The lexing doesn't token-for-token match Pygments, but outputs the same format.

**Comment by jneen** [comment]
(for example, several bugs in the pygments ruby and js lexers were fixed in rouge)

**Comment by jneen** [comment]
`$` by itself is a literal dollar sign in bash, so actually both are not quite accurate.

``` bash
; echo $
$
```

I think it's common for people to paste in bash samples with `$` at the front, which is why it's `gp` - `Generic.Prompt`.

**Comment by parkr** [comment]
Ah, ok. I also noticed a weird problem.

Pygments:

![screen shot 2015-01-31 at 1 45 59 pm](https://cloud.githubusercontent.com/assets/237985/5989958/89e32aac-a94f-11e4-863e-540771738aa1.png)

Rouge:

![screen shot 2015-01-31 at 1 46 32 pm](https://cloud.githubusercontent.com/assets/237985/5989959/a4b6910c-a94f-11e4-9168-f8e27b8689fa.png)

Is my Pygments stylesheet missing something?

**Comment by parkr** [comment]
To duplicate:

```bash
$ git clone git://github.com/jekyll/jekyll.git jekyll
$ cd jekyll
$ vim site/_config.yml # change `highlighter` to `rouge`
$ bundle exec rake site:preview
```

Then go to http://localhost:4000/docs/plugins/#converters

**Comment by jneen** [comment]
welp that's not intended behavior. I'll take a look tomorrow.

**Comment by jneen** [comment]
alternatively, if you could try to repro using ./bin/rougify, that'd be even more convenient.

**Comment by parkr** [comment]
HA! Turns out it was me all along:

```diff
diff --git a/lib/jekyll/tags/highlight.rb b/lib/jekyll/tags/highlight.rb
index 0305f1c..36cf93c 100644
--- a/lib/jekyll/tags/highlight.rb
+++ b/lib/jekyll/tags/highlight.rb
@@ -42,7 +42,7 @@ eos
       def render(context)
         prefix = context["highlighter_prefix"] || ""
         suffix = context["highlighter_suffix"] || ""
-        code = super.to_s.gsub(/^(\n|\r)+|(\n|\r)+$/, '')
+        code = super.to_s.gsub(/\A(\n|\r)+|(\n|\r)+\z/, '')
 
         is_safe = !!context.registers[:site].safe
 ```

D'oh. Sorry about that.

Curiously, the stylesheets still aren't lining up. Did you happen to document where your lexers deviate from Pygments?

**Comment by jneen** [comment]
Haha well, that'd do it for sure :)

**Comment by jneen** [comment]
I don't document where the lexers differ from pygments, as that would be an organizational nightmare.  The tokens are defined in `lib/rouge/token.rb`, and the list was lifted directly from Pygments.  I don't expect everything to be highlighted the same as in Pygments, just that it will be highlighted in a reasonable way using a stylesheet designed for Pygments.

**Comment by parkr** [comment]
Ok, cool. I'll figure it out. Thanks so much, @jneen!! Hope you were able to enjoy the sunshine today :smile:

**Comment by jneen** [comment]
Yes, I was!
