### ISSUE TITLE
if language is liquid arguments go missing

### ISSUE THREAD

**Issue by bekreatief** [jneen/rouge#237]
Hi
I am using rouge with jekyll. So far everything went perfectly fine, but when I tried to set the language to liquid, it did swallow part of my argument.
If i change the language to something else (css, html, scss tested) it's there, just the color hightlighting does not work, obviously.

Any idea why that is so?

[ three backticks ] html
{% raw %}{% for post in site.posts %}
    {% if post.author contains page.author %}
        {% include article_index.html %}
    {% endif %}
{% endfor %}{% endraw %}
[ three backticks ] 

result

![html](https://cloud.githubusercontent.com/assets/6460472/6246382/b19665ec-b768-11e4-9b3c-91b2fbab213f.PNG)

[ three backticks ] liquid
{% raw %}{% for post in site.posts %}
    {% if post.author contains page.author %}
        {% include article_index.html %}
    {% endif %}
{% endfor %}{% endraw %}
[ three backticks ] 

result:

![liquid](https://cloud.githubusercontent.com/assets/6460472/6246380/aa6e8ede-b768-11e4-8001-6b35240c247a.PNG)

**Comment by jneen** [comment]
Hm, that looks like Jekyll's Liquid processor might be swallowing it.  Can you try it with `rougify -l liquid`?

**Comment by bekreatief** [comment]
where would I put that?

**Comment by jneen** [comment]
Run it from the command-line.

```
$ rougify -l liquid
<paste liquid code>
<Ctrl-D>
```

**Comment by jneen** [comment]
Alternatively, and maybe simpler, put the liquid code in a file by itself and run

```
$ rougify -l liquid < file.liquid
```

**Comment by bekreatief** [comment]
Hmm really weird, but when I rebuild the site this morning it worked...
I have no idea why, but it is displayed now.

Still, thx a lot for your help!

**Comment by jneen** [comment]
Okay, glad to hear :)

**Comment by olliekav** [comment]
I'm having this issue as well when running liquid blocks. e.g.
```
{% if link.object.content contains img_tag %}
```
gets output as
```
{% if  contains  %}
```
I'm using this in markdown files in Middleman if that helps. Restarting doesn't solve it for me either.

**Comment by jneen** [comment]
@olliekav thanks for the report - could you try running your code through rouge manually?

``` bash
$ rougify -l liquid < your_code.liquid
```

**Comment by olliekav** [comment]
@jneen that did the same thing for me.
```
{% if  contains  %}
```

**Comment by jneen** [comment]
Okay, lastly, which version of rouge are you using? `rougify --version`

**Comment by olliekav** [comment]
1.8.0, I just updated as I needed the liquid lexer.

**Comment by olliekav** [comment]
There are also some other weird things happening, like `err` being wrapped around closing tags e.g.
```
{% assign page_has_image = false %}
```
The closing tag is output as
```
<span class="err">%}</span>
```

**Comment by jneen** [comment]
Ok, welp that's a bug.  I'll take a look tonight.  Thanks again for the report!

**Comment by olliekav** [comment]
Great, thanks!

**Comment by jneen** [comment]
Oh sorry one more thing - could you paste the specific code you're trying to highlight?

**Comment by olliekav** [comment]
Here you go...
```
{% assign page_has_image = false %}  
{% assign img_tag = '<' | append: 'img' %}  
{% if link.object.content contains img_tag %}
  {% assign src = link.object.content | split: 'src="' %}
  {% assign src = src[1] | split: '"' | first %}
    {% if src %}
      {% assign page_has_image = true %}
      {% assign image_src = src | replace: '_small', '' | replace: '_compact', '' | replace: '_medium', '' | replace: '_large', '' | replace: '_grande', '' %}
    {% endif %}
{% endif %}

{% if page_has_image %}
  <a href="{{ link.object.url }}">
    <img src="{{ image_src }}" alt="{{ link.object.title }}">
  </a>
 {% else %}
  <a href="{{ link.object.url }}">
    {{ 'blank-page-image.jpg' | asset_url | img_tag: shop.name }}
  </a>
{% endif %}
```

**Comment by jneen** [comment]
Thanks!

**Comment by jneen** [comment]
Pinging @RadLikeWhoa, could you take a look at this since you contributed the liquid lexer?

**Comment by RadLikeWhoa** [comment]
I'll have a look at this once I have some time. Might be in a week or two, though.
