### ISSUE TITLE
Implement a D lexer

### ISSUE THREAD

**Issue by jneen** [jneen/rouge#24]

**Comment by CyberShadow** [comment]
Here is my implementation of D highlighting for Colorer, a regex/XML-based editor highlighter:

Scheme: https://github.com/colorer/Colorer-schemes/blob/master/hrc/hrc/base/d.hrc
Test file: https://github.com/colorer/Colorer-schemes/blob/master/hrc/test/other/d-sample.d

I hope the size isn't off-putting. The Rouge implementation doesn't need to be as inclusive, as the above is meant for live text editing with outliner support.

**Comment by nikibobi** [comment]
I'm going to start working on this. I'll try to stay as close to the pygments [implementation](https://bitbucket.org/birkenfeld/pygments-main/src/859b2bce647cd212e39cd63f83f93f4083b232b2/pygments/lexers/d.py). I'll open a pull request when I have progress.
