### ISSUE TITLE
Ruby object attributes w/o parens in division treated as regex opener

### ISSUE THREAD

**Issue by brianwisti** [jneen/rouge#248]
This is Ruby 2.2.0, Rouge 1.8.0 on OS X.

When highlighting Ruby code, a division symbol `/` following an object attribute triggers rendering as CSS class `sr`, and rendering doesn't go back to normal until another `/` is encountered. A workaround is to add parens to the attribute.

Here's a minimal sample.

``` ruby
x.a / 1 # / Minimal case
x.a() / 1
```

And here's how it renders.

![screen shot 2015-03-15 at 11 40 09 pm](https://cloud.githubusercontent.com/assets/161212/6661624/ac3039f8-cb6c-11e4-822a-cf25abf941c1.png)

Thanks for your time!

**Comment by jneen** [comment]
Thanks for the report!  Luckily I think that turned out to be easy.  Can you see if I've fixed it on master? (as of https://github.com/jneen/rouge/commit/98055597a0f1f4d2d74b240b5e56909e368eb874)

**Comment by brianwisti** [comment]
Yes indeed. The issue is resolved using a gem built from master.

**Comment by jneen** [comment]
Cool, thanks!

**Comment by alex-felix** [comment]
this can be closed 👍
