### ISSUE TITLE
Powershell support

### ISSUE THREAD

**Issue by XhmikosR** [jneen/rouge#251]
Hi.

I was wondering if it would be easy to add Powershell support.

**Comment by aaroneg** [comment]
This is done.

**Comment by XhmikosR** [comment]
Indeed, thanks.

**Comment by stefanvangastel** [comment]
@aaroneg What version of powershell is supported?

**Comment by aaroneg** [comment]
I gathered most of the information while running windows 7, so I'd imagine
it's pretty close on version 3. It's a pretty simple lexer if memory
serves, you should be able to add whatever you need to it.

**Comment by stefanvangastel** [comment]
@aaroneg Cool, a colleague opened a PR: https://github.com/jneen/rouge/pull/757
