### ISSUE TITLE
http://rouge.jayferd.us/demo is not working.

### ISSUE THREAD

**Issue by v0lkan** [jneen/rouge#253]
When I browse it using Chrome (or any browser per se), I get a loading spinner on the tab, and the page does not load.

After waiting long enough I get a

"
Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE
"

Either a DNS thing, or some dynos not booting in heroku, not sure.

**Comment by jneen** [comment]
Welp, that's because it's moved to rouge.jneen.net. Where did you find that link?

**Comment by rumpelsepp** [comment]
```

**Comment by jneen** [comment]
Cool, links fixed. Thanks for reporting!
