### ISSUE TITLE
Ruby highlight bug

### ISSUE THREAD

**Issue by Paxa** [jneen/rouge#258]
``` ruby
# Your business timezone 
Time.zone = "Asia/Jakarta"

def to_server_time(time_str)
  time = Time.zone.parse(time_str)
  server_offset = Time.now.getlocal.utc_offset.to_f / 1.hour
  time.in_time_zone(server_offset)
end

to_server_time('00:30') # => Sun, 28 Sep 2014 17:30:00 WET +00:00
to_server_time('00:30').strftime("%H:%M") # => "17:30"
```

Will be shown as:
![screen shot 2015-04-26 at 13 44 56](https://cloud.githubusercontent.com/assets/26019/7336203/813a3572-ec1a-11e4-9154-ec3e6eaaeba5.png)

**Comment by rodrigoargumedo** [comment]
That is definitely a bug. Can you provide more details about it?

Though, the `/` should not be escaped at all, in my opinion.

**Comment by alex-felix** [comment]
this seems to not happen anymore... maybe it has been fixed?
http://rouge.jneen.net/pastes/mjen
can you try again @Paxa with your setup and the up to date gem?

**Comment by alex-felix** [comment]
it got fixed for this issue by @jneen - this can be closed 👍 
https://github.com/jneen/rouge/issues/248

**Comment by gfx** [comment]
Great.
