### ISSUE TITLE
Add Support for React JSX 

### ISSUE THREAD

**Issue by jbbr** [jneen/rouge#275]
The JavaScript framework "React" by Facebook does introduce a syntax extension for JavaScript.
It adds something which looks like XML in JavaScript.

As React is getting a lot of attention in the JavaScript frontend framework world (e.g. 23000+ stars on github), it would be great to have support for JSX highlighting with rouge.

React Framework: https://github.com/facebook/react
JSX Specs: https://facebook.github.io/jsx/

File extensions: .js, .jsx

**Comment by jneen** [comment]
I'd gladly merge this PR.  I'd recommend subclassing the javascript lexer, much like `C++` subclasses `C`.

**Comment by MForever78** [comment]
I'm seeing that the latest version of rouge doesn't support jsx yet. Is there any progress now?

**Comment by pragdave** [comment]
I just wrote a rough-n-ready JSX lexer. Before submitting a PR, I wonder if people who actually know how this is supposed to work could review it.

https://gist.github.com/pragdave/fc56273a8f6cd772caac


Cheers

Dave

**Comment by pragdave** [comment]
Oops, I forgot–there's a hole in that code where I meant to ask y'all.

One form allowed in JSX is `<tag name={ javascript code }>`. To support that, I have to add the expression recognizer to the `:attribute` state. But I also then have to pop the state, and I can't work out how to do that.

**Comment by flipace** [comment]
i'd really like to use this - any idea when it will be ready?

**Comment by jbbr** [comment]
@flipace Seems like the no core developer is working on this right now but they are open to pull-requests. So it depends on external contributions.

@pragdave Thanks for your gist. I will have a look at your code but unfortunately I'm not familiar with rouge lexers and advanced regex at all. Maybe @jneen or other core developers could help you with the `:attribute` state problem?

**Comment by zackify** [comment]
Any status update on this?

**Comment by jneen** [comment]
No

**Comment by enriquecaballero** [comment]
Seriously. This is WAY overdue.

**Comment by enriquecaballero** [comment]
The same could be said about the comment above mine.

**Comment by enriquecaballero** [comment]
@segiddins Have you not seen this? https://github.com/jneen/rouge/pull/336

**Comment by suitupalex** [comment]
@enriquecaballero Looks like the PR isn't finished and the author of it hasn't worked on it.

**Comment by pragdave** [comment]
We're using that PR in production. I just have one pending question which
no one has answered.

I have to say I'm disappointed in the way this project deals with the
community.

**Comment by jneen** [comment]
Hi all. I apologize for the continued delay in this and other issues. Until today, I was maintaining rouge in my spare time, which got squeezed to basically nothing through a combination of full-time work and a series of medical issues. In addition, at least two for-profit corporations with a lot of traffic began using rouge, which greatly multiplied the amount of pull requests and issues. I simply could not keep up. Good news is one of them hired me to help sort out this very kind of issue, so I can actually dedicate time to maintaining the project and vetting pull requests.

@pragdave, @enriquecaballero, and @silvenon, I ask that you please take a step back in the future and consider the situations that other open-source maintainers might be dealing with while working for free to make tools for you to use.

Now, with regard to this specific issue, the pull requests mentioned here are not yet mergeable, as they either copy-paste the javascript lexer wholesale, or attempt to parse the embedded XML with a single regular expression.

Going forward, I'm hoping to take up @nayaabkhan on their offer to help fix the issues with #336, with my help as I'm available, so hopefully we can start seeing some movement on this. Thank you all for the work you've put in.

**Comment by jneen** [comment]
@pragdave: To answer your question, you can pop the lexer stack either by passing the symbol `:pop!` instead of the name of the new state, or by calling the `pop!` method in the action block. The lexer API is documented in the README.

**Comment by jneen** [comment]
@pragdave: ah i see i misread your question - for an embedded language i'd recommend delegating it piece by piece to a javascript lexer, taking care to push state at every `{` and pop at every `}`, and avoid curlies that are in strings, etc. This is a pain, but it's more or less what the JSX implementation has to do as well, in order to support "scan to the balanced curly brace" embedded syntax.

**Comment by silvenon** [comment]
@jneen if this is about my 👎, I was not downvoting the fact that you didn't have an ETA, just the way that you said it. But I was only adding to the negativity, I see that now. I'm really glad that you are well now and I'm sorry for displaying lack of appreciation, I really love this project and what you do, I understand what a pain it can be to maintain it.

👍

**Comment by drobati** [comment]
Looking forward to this. Just setup GitLab's CI and noticed our JSX files weren't detected.

**Comment by jneen** [comment]
JSX is now supported on master. Thank you all for your work.

**Comment by joshbuchea** [comment]
@jneen awesome! I've been very anxiously awaiting this feature. Thank you to everyone involved for all of your effort!

**Comment by jbbr** [comment]
Thanks everyone involved. I think this can be closed now as it's not only in master but also in the release v2.0.6.
Maybe someone will find the time to have a look at JSX support for Typescript too, #516
