### ISSUE TITLE
C function prototype syntax highlighting broken if space before semicolon

### ISSUE THREAD

**Issue by JonathonReinhart** [jneen/rouge#277]
Parsing the following line of C code yields a very broken result:
```
void foo() ;
```
(note the space before the closing parenthesis and the semicolon)

The result looks like this:
```
void void foo() ;() void foo() ;
```

@stanhu indicated:

> I fed the input `static void func () ;` into the lexer, and got these tokens back:
> ```
[["Keyword", "static"],
 ["Text", " "], 
 ["Keyword.Type", "void"], 
 ["Text", " "], 
 ["Name.Function", "static void func ( ) ;"], 
 ["Text", " "], 
 ["Punctuation", "("], 
 ["Text", " "], 
 ["Punctuation", ")"],
 ["Text", " "], 
 ["Punctuation", "static void func ( ) ;"], 
 ["Text", " "]]
```


Live example: http://rouge.jneen.net/pastes/RM8

This bug was originally reported in [GitLab CE (#1890)](https://gitlab.com/gitlab-org/gitlab-ce/issues/1890).

**Comment by JonathonReinhart** [comment]
https://github.com/jneen/rouge/blob/dbdd4e7d249606543831dba63efc2737b7d6ad90/lib/rouge/lexers/c.rb#L136
```

        # functions
        rule %r(
          ([\w*\s]+?[\s*]) # return arguments
          (#{id})          # function name
          (\s*\([^;]*?\))  # signature
          (#{ws})({)         # open brace
        )mx do |m|
          # TODO: do this better.
          recurse m[1]
          token Name::Function, m[2]
          recurse m[3]
          recurse m[4]
          token Punctuation, m[5]
          push :function
        end
        # function declarations
        rule %r(
          ([\w*\s]+?[\s*]) # return arguments
          (#{id})          # function name
          (\s*\([^;]*?\))  # signature
          (#{ws})(;)       # semicolon
        )mx do |m|
          # TODO: do this better.
          recurse m[1]
          token Name::Function
          recurse m[3]
          recurse m[4]
          token Punctuation
          push :statement
        end
```

Why do the function (definitions) and function declarations look so much different? Specifically in the decl case, the `Name::Function` and `Punctuation` tokens have no arguments (like `m[2]` and `m[5]`).

**Comment by jneen** [comment]
Well I think you may have found the bug.

**Comment by stanhu** [comment]
Yes, I confirmed that adding the arguments fixes the bug. I have a test for this that I'll submit.
