### ISSUE TITLE
Syntax highlighting of last line incorrect if not followed by an endline

### ISSUE THREAD

**Issue by mojavelinux** [jneen/rouge#279]
If there is an endline missing from the source string, then the syntax highlighting isn't working correctly on the last line.

An example of this can be seen on the website (which I'm able to reproduce locally). See http://rouge.jneen.net/pastes/lAp. You'll notice that the inline comment on the last line is not styled as a comment. If you add an endline to the source and rerun it, then it highlights correctly. See http://rouge.jneen.net/pastes/kXn.

The simplest solution to this problem is to add a trailing endline to the incoming source if it's missing and then strip after the tokens are created.

**Comment by mojavelinux** [comment]
This seems to be a problem if one of the rules the lexers explicitly match an endline. In this particular example, the Groovy lexer looks for a trailing endline to match a single-line comment. It should be looking for an end of line character instead (`$`). Some lexers match this scenario correctly.

**Comment by jneen** [comment]
Yep, that's a bug.  Good catch.

**Comment by mojavelinux** [comment]
:+1: 

Just so you know, this fix only address one of many places where the lexer rules miss a highlight on the last line. For instance, here's another: https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/sql.rb#L92. I have not done a full audit.

**Comment by mojavelinux** [comment]
The SQL issue was fixed by #360.
