### ISSUE TITLE
Maintenance Release 1.9.1?

### ISSUE THREAD

**Issue by rumpelsepp** [jneen/rouge#283]
May I ask you to bump the version number to 1.9.1? Would be nice, because https://github.com/gitlabhq/gitlabhq/pull/9341 is blocked by https://github.com/jneen/rouge/commit/03b03c598b6108294d3671988bc97f27ce4f9897.

**Comment by jneen** [comment]
Is it possible to depend on a git version for now? I have some formatter work I wanna finish first.

**Comment by rumpelsepp** [comment]
No idea, I'll have to investigate first.

**Comment by stanhu** [comment]
+1

It seems to be the practice in GitLab that all gems use a released version, not a specific git version. Could we get a version bump so we can migrate back to rouge?

**Comment by jneen** [comment]
Odd.

**Comment by jneen** [comment]
In this one instance, it does happen to be time for a release.  However, I strongly suggest that you start using git gems occasionally in the cases that I don't have time to cut one after every PR.

**Comment by jneen** [comment]
1.9.1 is released.

**Comment by rumpelsepp** [comment]
Thank you!
