### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by raymens** [jneen/rouge#285]
F# syntax is heavily based on OCaml

**Comment by jimmykeen** [comment]
Any progress in here?

**Comment by raymens** [comment]
Yup, in #286 . Waiting for review.

**Comment by Alxandr** [comment]
Any chance of getting this backported for 1.x?

**Comment by jneen** [comment]
Unlikely, no. I suggest upgrading to 2.x anyways, the API is much cleaner - and you can always just sub `HTML` -> `HTMLLegacy` if you're really lazy :].

**Comment by Alxandr** [comment]
I'm using jekyll, so I'm not sure if I can even get it to use 2.0. I'm completely new to ruby, but from my attempts at least, I couldn't get it working with rouge 2 because it complained about wrong dependencies.

**Comment by jneen** [comment]
I would suggest opening a ticket over at Jekyll asking them to upgrade.
