### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by donnut** [jneen/rouge#305]
I would love to have Typescript syntax highlighting in gitlab. Typescript is a superset of Javascript. I could try to add Typescript to rouge, but that is probably a 90% copy-paste activity. What would be the best way to proceed?

**Comment by knutaldrin** [comment]
The best way to do this would be to inherit from the javascript lexer, and extend it (in much the same way as c++ extends the c parser). Thus you won't have to copy-paste. ;)

**Comment by vojtechhabarta** [comment]
I would also like to have TypeScript syntax highlighting on gitlab. Would it be possible (technically and legally) to reuse some library rather than developing it from scratch? GitHub has support for TypeScript and I personally use highlight.js.

**Comment by tommyZZM** [comment]
:+1

**Comment by attilacsanyi** [comment]
+1

**Comment by jneen** [comment]
I'd happily merge this pull request, but I don't have time to implement it myself.

**Comment by markvandenbrink** [comment]
+1

**Comment by jneen** [comment]
@donnut If you want to take a crack at this, I'd suggest subclassing the javascript lexer and using `prepend` and `append` - you can see the QML lexer for an example of this.

**Comment by jneen** [comment]
...that way there's no copy/paste.

**Comment by okaufmann** [comment]
+1

**Comment by sanex3339** [comment]
+1

**Comment by binarious** [comment]
+1

**Comment by zorend** [comment]
+1

**Comment by dchacke** [comment]
+1

**Comment by Inspiravetion** [comment]
+1

**Comment by tflori** [comment]
+1

**Comment by jerive** [comment]
+1

**Comment by dotnetautor** [comment]
+1

**Comment by duyaokun** [comment]
+1
