### ISSUE TITLE
Should `Keyword::Constant` match the color of integers, floats,...?

### ISSUE THREAD

**Issue by HarryLovesCode** [jneen/rouge#319]
Below you'll notice that `true` has the same color as the return type `u64`.

![screen shot 2015-09-23 at 5 06 22 pm](https://cloud.githubusercontent.com/assets/12660259/10059822/2c7705e8-621b-11e5-951f-73c30c509dce.png)

Should the color of `true` match that of a literal such as `1.0f32`? Below shows what it would look like...

<img width="710" alt="screen shot 2015-09-23 at 5 47 07 pm" src="https://cloud.githubusercontent.com/assets/12660259/10059821/2c76ff76-621b-11e5-928b-3416c4f80220.png">

This is the way other syntax highlighters highlight (such as Atom, C9 Ace,...). Here is Atom for a comparison...

<img width="427" alt="screen shot 2015-09-23 at 5 51 48 pm" src="https://cloud.githubusercontent.com/assets/12660259/10059948/dd994340-621b-11e5-9fb0-8b97eb702e31.png">

The reason this is an issue and not a pull request is because I'm unsure if the modifications to the stylesheet would screw with languages other than Rust.

**Comment by jneen** [comment]
Rouge takes the lead of Pygments here, which semantically highlights the former as `Keyword::Constant` and the latter as `Number::Float`, which can be colored independently depending on which stylesheet you're using.

**Comment by jneen** [comment]
The reason we use the same tokens as Pygments is to allow for pygments-stylesheet-compatible HTML output.
