### ISSUE TITLE
Syntax Highlighting Breaking

### ISSUE THREAD

**Issue by PatchesNULL** [jneen/rouge#321]
Python syntax highlighting breaks on specific code lines.

"raise Exception from None"

The above is the only line I've seen do it, though my line is actually "raise BadIDError(error) from None". Commenting out this line restores syntax highlighting until it encounters another line similar or exactly the same.

This is a repost from https://gitlab.com/gitlab-com/support-forum/issues/360

**Comment by stanhu** [comment]
`raise...from...` is a Python-3 definition:

https://docs.python.org/3/reference/simple_stmts.html#raise

The Python lexer doesn't currently support this; it's mistakenly interpreting the `from None` as an import statement.

**Comment by jneen** [comment]
Hi @PatchesNULL, thanks for the report!  We don't yet support all python 3 features yet unfortunately - that's been on the TODO list for some time. The issue here seems to be that the `from` keyword enters a `:fromimport` state which expects a namespace, which I imagine also breaks `yield from` and friends.

**Comment by jneen** [comment]
I don't have a whole lot of time right now, but if one of yall feel like either massaging the python lexer to fit both python 2 and 3 or splitting them into two lexers, I'd be super grateful.  The former would be nicer if it's workable.

**Comment by PatchesNULL** [comment]
I'd love to help, but it'll have to be someone else. Got sent here by the GitLab people, and I don't actually know ruby :P

**Comment by mordervomubel** [comment]
I don't really know ruby either, but I and @PatchesNULL got it fixed. Is this good for a merge?
https://github.com/jneen/rouge/pull/324

**Comment by PatchesNULL** [comment]
Indeed. You're welcome to close the issue. We worked on it together so can confirm it fixed my issue.

**Comment by jneen** [comment]
Closed by #324.
