### ISSUE TITLE
Praat lexer fails with functions passed as arguments to other functions

### ISSUE THREAD

**Issue by jjatria** [jneen/rouge#334]
If a function is passed as an argument to a procedure delimited with colons, the lexer fails to find a proper exit of the `comma_list` context. Example:

    @proc: a, selected("string"), b
    # Error

I think the `comma_list` context needs to be redesigned, since it doesn't really need to be recursive: a [non-recursive version](https://bitbucket.org/birkenfeld/pygments-main/src/73115a27a7dd363e50c0996810b2e6b75a0849fd/pygments/lexers/praat.py?at=default&fileviewer=file-view-default) of basically the same lexer was pushed to pygments, and that version correctly lexes this.

**Comment by jneen** [comment]
Good catch.  I agree that the non-recursive version would be preferable.  Do you have time to put together a PR of this?

**Comment by jjatria** [comment]
Not just now. But if you give me a week or so I think I'll have time to get around to it.

**Comment by jjatria** [comment]
Welp, it was definitely _not_ a week or so. But there it is!

Comments welcome!
