### ISSUE TITLE
Highlight a specific line

### ISSUE THREAD

**Issue by nasht00** [jneen/rouge#342]
Jekyll 3 has switched from Pygments to Rouge.

One thing I used to do with Pygment is to highlight a specific line in a code block (`hl_lines`).

Are there plans to support such a feature?

**Comment by MischaDeNola** [comment]
Is there a way to do this with Rouge right now? This would solve a big problem converting from pygments.

**Comment by jneen** [comment]
That would be a Jekyll feature - please open an issue with them.

**Comment by nasht00** [comment]
Why would it be a Jekyll feature?

It is a feature of Pygment (See on `hl_lines` http://pygments.org/docs/formatters/), which Jekyll used.

When they switched to Rouge, we lost that feature.

**Comment by IdanAdar** [comment]
+1 for this feature in Rouge.

**Comment by jrfnl** [comment]
Duplicate of #264
