### ISSUE TITLE
List of stylesheets examples?

### ISSUE THREAD

**Issue by nasht00** [jneen/rouge#343]
The documentation just says that Rouge is compatible with my existing Pygments stylesheets.
But if I am starting from scratch, the fact that it's compatible with some other product is not very interesting to me.

Can you publish more information about what the CSS should look like?

Maybe provide a list of existing examples we can use?

I plan to use the line numbers feature, and the existing stylesheets I found made it look horrible.

**Comment by jneen** [comment]
Hi! If you're starting from scratch, I recommend creating a rouge theme (see `lib/rouge/themes/thankful_eyes.rb` for an example).  Then call `MyTheme.render('.highlight')` (or whichever CSS class you have on your highlighted blocks) and it should give you the CSS.  The highlight token for line numbers is `Generic::Lineno`.

**Comment by nasht00** [comment]
I'm actually using Rouge as part of Jekyll 3.0, so there is no ruby code involved here.

All I can do is provide a CSS file (and yes `.highlight` is the default css class).
Is there an easy way to get the compiled CSS file from one of those themes?

**Comment by waylan** [comment]
All of the default Pygments themes have been generated as CSS files and posted on GitHub [@richleland/pygments-css](/richleland/pygments-css). You can copy any of those files and use them. No need to install Pygments and run it from the command line to generate the CSS files yourself. A [preview](http://richleland.github.io/pygments-css/) of each theme is also available.

Note that all of those themes use `.codehilite` as the default class. You may need to tell Rouge to use that class or edit the CSS file to use Rogues' `.highlight` class.

**Comment by nasht00** [comment]
I'm closing this, however, I think it would be nice to post those links somewhere, in the readme or the website.
Because like I said, new users (like myself) don't care that it's "pygments compatible" if they never used Pygments before.

**Comment by mbmasuda** [comment]
I know this is an old thread, but I found it looking for the CSS stylesheets.  I found that I could easily create the stylesheet in a Rails project by creating a file called `app/assets/stylesheets/rouge.css.erb` and putting this content in it:

```
<% require 'rouge' %>
<%= Rouge::Themes::Github.new.render %>
```

**Comment by corysimmons** [comment]
I'm sure I'm doing something stupid, but adding a stylesheet whatever the correct way is was taking more than 5 minutes. Could someone please add a tip or something on the Rouge website on the preferred way to add stylesheets?

In the meantime: If you're using Jekyll, find a theme you like on https://github.com/richleland/pygments-css (not the 100's of themes you were promised, but whatev), grab the CSS, `@import` it, Find/Replace `codehilite` with `highlight`.

If someone points me in the direction of the 100's of Pygment themes -- and they all follow the same structure -- I'll convert them all to Rouge and make some sort of theme viewer for them.

**Comment by jneen** [comment]
Hi @corysimmons. The distinction between `codehilite` and `highlight` is made by Jekyll, not by Rouge. If you'd like them to change it, I suggest you take it up with them.

**Comment by svenevs** [comment]
I stumbled upon this after finding the above linked `pygments-css` page and was curious about what all this `codehilite` stuff was.  Anyway, for `jekyll` users, you may want to save yourself the extra step and just use [the `jekyll` fork](https://github.com/jwarby/jekyll-pygments-themes) 😄 

It's worth mentioning that this appears to be an artifact at this point, if you run `pygmentize -S default -f html`, they removed the preceding `.highlight`.  Or at least it isn't there in `Pygments version 2.1.3`.

**Comment by hdante** [comment]
Hello, I'd like to request reopening this issue, to have a full, separate documentation of the stylesheet format used by rouge. I ask this, because rouge is generating different styles than pygments (the example I have is that rouge doesn't style the C include file name as "cpf", but pygments does).
