### ISSUE TITLE
Ability to preserve custom content

### ISSUE THREAD

**Issue by rdavila** [jneen/rouge#356]
I'm wondering if it's actually possible to do this:

If I have a line with this content: `class <span class="special">MyClass</span>`

Then I only want the `class` keyword to be highlighted and the rest of the content should be untouched, I mean the `span` tag and all the related content should not be tokenized.

I'm thinking in creating a custom Lexer which can be configured to ignore that text and call some sort of parent Lexer to do the real highlighting, however I'm not sure if it's a good approach to solve this problem.

**Comment by jneen** [comment]
Hi! Do you mean you want to inline that HTML into the output of the HTML formatter/

**Comment by rdavila** [comment]
@jneen yes, the `span` tag is being tokenized and the content is being shown in a raw format instead of only seeing `MyClass` with it's custom CSS styling.

**Comment by jneen** [comment]
So a possible issue here is that lexers do not create HTML - they create token streams.  This is so that content can be rendered to HTML, ANSI codes, and potentially BBCode or other systems.  I would recommend writing a lexer that uses `delegate` to send to a parent lexer, and yields a special token when it sees some sort of delimiter. You can declare a new token with `Rouge::Token::Tokens.token(:SpecialThing, 'st')`, where `'st'` is what will end up as the CSS class for that token.

**Comment by rdavila** [comment]
@jneen thanks for the insight, I'll try to implement it and let you know if I found any issues.

**Comment by rdavila** [comment]
@jneen looks like I'm missing something in my lexer, I have this one:

```ruby
Rouge::Token::Tokens.token(:MyToken, 'st')

class MyLexer < Rouge::RegexLexer
  title "My Lexer"
  tag 'my_lexer'

  state :root do
    rule /world/, MyToken
    rule /.+/ do
      delegate Rouge::Lexers::Ruby
    end
  end
end

puts Rouge.highlight('hello world', 'my_lexer', 'html')
```

It's generating this ouput:

`<pre class="highlight"><code><span class="n">hello</span> <span class="n">world</span></code></pre>`

but I want to generate this one:

`<pre class="highlight"><code><span class="n">hello</span> <span class="st">world</span></code></pre>`

So looks like it's passing all the token to the Ruby lexer.

**Comment by rdavila** [comment]
I just tried to negate the regexp in the rule that delegates and it works :)

```ruby
class MyLexer < Rouge::RegexLexer
  title "My Lexer"
  tag 'my_lexer'

  state :root do
    rule /world/, MyToken
    rule /[^(world)]/ do
      delegate Rouge::Lexers::Ruby
    end
  end
end
```

**Comment by rdavila** [comment]
@jneen I'm having some trouble when trying to implement the right rules, I think it's due to my incomplete understanding about how `rules` and `states` works. I've this custom Lexer:

```ruby
Rouge::Token::Tokens.token(:MyToken, 'st')

module Rouge
  module Lexers
    class CustomLexer < TemplateLexer
      title "Custom Lexer"
      tag 'custom_lexer'

      state :root do
        rule %r{<span class='high'>(.*?)</span>} do |match|
          token MyToken, match[1]
        end

        rule /^(?!.*(<span class='high'>.*?<\/span>)).+/ do |m|
          delegate parent, m[0]
        end
      end
    end
  end
end
```

When I have a string like this: `"puts 'one' <span class='high'>hoho</span> puts 'two'"`

I want `puts 'one' ` and ` puts 'two'` to be processed by the second rule, and `<span class='high'>hoho</span>` to be processed by the first rule.

Another scenario is when I have a string like this: `"puts 'hello'"`, it should only be processed by the second rule.

Right now I'm getting an incomplete processed string like this: `"<span id=\"LC1\" class=\"line\"><span class=\"err\">puts &#39;one&#39; </span><span class=\"st\">hoho</span></span>"`. Only the `span` tag was processed and the rest of the text was not processed by the second rule.

**Comment by jneen** [comment]
Please try running with the `:debug` flag on.

**Comment by rdavila** [comment]
Thanks a lot for your help @jneen, the `:debug` option is pretty useful. I have found an error when trying to implement your suggestion, looks like it's pretty related to the ERB lexer: #357 

I'm going to close this issue since you have already solved my question.
