### ISSUE TITLE
Highlighting of comment in SQL is incorrect if comment is on last line and there is no newline

### ISSUE THREAD

**Issue by duffn** [jneen/rouge#360]
If there is a comment in SQL on the last line of the code and there is no newline, the comment is highlighted as regular code and not as a comment.

http://rouge.jneen.net/pastes/ajM

![screen shot 2015-12-23 at 10 18 06 am](https://cloud.githubusercontent.com/assets/3457341/11981281/847609a8-a95e-11e5-964e-4a794310e667.png)

**Comment by julp** [comment]
Hi,

the SQL lexer may not be the only one to be concerned by this issue.

**Comment by jneen** [comment]
Fixed in 1.11.0 by #364.
