### ISSUE TITLE
Missing support for Ruby heredocs method chaining

### ISSUE THREAD

**Issue by simonc** [jneen/rouge#363]
Hi there :)

I tried to add support for Ruby heredocs method chaining but I don't really know the lexer DSL for now (and sadly lack the time to dig into it).

I'll just create an issue to document the missing feature.

What I'm talking about is the support for this kind of code:

``` ruby
puts <<-END.strip_heredoc
  Hello World
    How are you tody ?
  Cheers
END

puts <<~END.strip_heredoc
  Hello World
    How are you tody ?
  Cheers
END
```

**Comment by zhengjia** [comment]
@simonc Looks like this is already working. With your example:

![screen shot 2017-11-07 at 6 55 21 pm](https://user-images.githubusercontent.com/192933/32526116-475cf7ce-c3ed-11e7-97d1-11338bcf5d35.png)

What are you expecting?

**Comment by simonc** [comment]
@zhengjia I opened this 2 years ago, I think it's been fixed since then ^^ Let's close this issue! Thanks for the reminder.
