### ISSUE TITLE
Retain the language identifier in the generated HTML

### ISSUE THREAD

**Issue by clns** [jneen/rouge#379]
Currently the parsed markdown generates the following HTML code:

``` html
<div class="highlighter-rouge">
  <pre class="highlight">
    <code>
      <span class="nx">alert</span>
      ...
    </code>
  </pre>
</div>
```

Is it possible to retain the language identifier (in this case `js`) into the HTML? Maybe as a `data-lang` attribute, similar to pygments, e.g.:

``` html
<code data-lang="js">
```

I'm not sure if this is the right place for this issue, or maybe it should be in the [kramdown](https://github.com/gettalong/kramdown) repo, so sorry if I got it wrong.

**Comment by ethanresnick** [comment]
+1. Having the language identifier in `data-lang` or in a (prefixed) classname would be really nice!

This bit me when trying to switch to Rouge from Pygments.

**Comment by vincent-zurczak** [comment]
+1

I have switched to Jekyll 3.x for Github pages and this option would be very convenient. We have tons of code snippets and we used to customize the CSS per language. Keeping the language as a data-lang attribute or as a CSS class (`pre class="highlight language-html"`) would be welcome.

If we do not want to make it the default behavior, maybe this feature could be enabled through an option.

**Comment by KobaKhit** [comment]
+1 
I have code chunks which are text output and I want the background for them to be white. Having the language identifier allowed me to do so. I use Jekyll with redcarpet which has this feature. But with kramdown the language identifier is not retained.

**Comment by chaosdefinition** [comment]
+1
I really need this feature for syntax highlighting in my Jekyll-based website, where I use [PrismJs](http://prismjs.com/). It is a JavaScript syntax highlighter and it needs the class `language-*` in `pre` to work.

**Comment by pbeshai** [comment]
FYI, I figured out a way to work around this limitation. Since Kramdown accepts [inline attribute list](http://kramdown.gettalong.org/syntax.html#inline-attribute-lists), you can specific the `language-js` class name after your code blocks this way:

```
\```js
const foo = 'bar';
\```
{: .language-js}
```

*(ignore the \, I don't know how to escape triple backticks in code blocks)*

Prism will undo the highlighting done by Rouge if you're using Prism, but otherwise you can just use this method to give the blocks a classname corresponding to the language you chose.

**Comment by jneen** [comment]
Hi all! This is a Jekyll issue, not a Rouge one - Rouge is only responsible for generating the highlighted HTML - what is done with it beyond that is the library user's responsibility, in this case Jekyll's.
