### ISSUE TITLE
start_inline passed manually

### ISSUE THREAD

**Issue by parkr** [jneen/rouge#381]
Hey @jneen!

I'd like to be able to use `start_inline` (which you write about in https://github.com/jneen/rouge/issues/187#issuecomment-61843772) with our `{% highlight %}` liquid tag. Can they be passed in [via formatter initializer](https://github.com/jekyll/jekyll/blob/v3.0.2/lib/jekyll/tags/highlight.rb#L102). It's not documented in the README so I wasn't sure. Ideally, a user would be able to use `{% highlight php start_inline %}`.

Thanks! Sorry if this is vague; I can clarify if needed. Been going through tons of issues after GitHub upgraded to Jekyll 3 and Rouge. :)

**Comment by jneen** [comment]
Does your platform use `find_fancy`? If so, you can use `php?start_inline=1`.

**Comment by parkr** [comment]
We do use `find_fancy`! I'll investigate passing options via the `lang` parameter.

**Comment by parkr** [comment]
It does, thank you. This works perfectly with triple backtick code blocks in kramdown. 

Thanks, @jneen!

**Comment by jneen** [comment]
yay, glad to hear it!
