### ISSUE TITLE
Add support for documentation comments

### ISSUE THREAD

**Issue by klmr** [jneen/rouge#388]
While rewriting the R lexer in #383 I’ve come across a problem: There doesn’t seem to be support for documentation comments (Doxygen, Roxygen, C# XML comments, RDoc), in general, any kind of composite markup.

For instance, consider the following R code:

```r
#' @param x the object
#' @return A logical indicating whether \code{x == 0}
is_zero = function (x) x == 0
```

Ideally, the whole block should be marked as `Comment::Doc`. *In addition*, the `@param` etc directives and the pseudo-LaTeX code should be highlighted as keywords. My current approach looks as follows:

```ruby
state :root do
  rule /#'/, Comment::Doc, :roxygen
  …
end

state :roxygen do
  rule /[^@\n]+/, Comment::Doc
  rule /@\w+/, Name::Attribute
  rule /\n/, Comment::Doc, :pop!
end
```

However, this approach doesn’t cope well if the user-provided stylesheet looks as follows (say):

```css
cd {
    background: #CCC;
    font-style: italic;
}
```

… since the generated HTML code will currently look as follows:

```html
<span class="cd">#' </span><span class="k">@param</span><span class="cd"> x the object</span>
```

Instead, either of the following would need to be produced:

* Nested HTML tags:

    ```html
    <span class="cd">#' <span class="k">@param</span> x the object</span>
    ```

* Multiple CSS class names

    ```html
    <span class="cd">#' </span><span class="cd k">@param</span><span class="cd"> x the object</span>
    ```

* Separate token types (e.g. `Comment::Doc::Keyword`)

**Comment by jneen** [comment]
Hi @klmr, we don't support nesting tokens, and unfortunately it would complicate the model enough that I don't intend to support them in the future.

**Comment by klmr** [comment]
Ah, that’s a shame.
