### ISSUE TITLE
PHP Syntax highlight breaks

### ISSUE THREAD

**Issue by message** [jneen/rouge#399]
Syntax breaks at `{$e->getMessage()}` part

```php
<?php

function a() { echo "a";}
Log::error("Unable to get full account status for user with ID {$userId}, error: {$e->getMessage()}");
function b() { echo "b";}
```

![screenshot from 2016-02-18 00 54 45](https://cloud.githubusercontent.com/assets/492026/13127812/3ada25b0-d5da-11e5-96e5-745f0a350480.png)

**Comment by jneen** [comment]
Thanks for the report! Fixed by d173687.
