### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by pbregener** [jneen/rouge#411]
I am slightly worried about this project's activity. Over the last weeks and months several largish projects have adopted Rouge and many PRs were filed to extend and improve it. This includes both bugfixes and new lexers (also for languages that were requested specifically). But the last PR was merged more than 2 months ago.

I know that no one is getting paid for developing or maintaining here, but it's too bad that all the new features, fixes and great work are not quite getting the attention they deserve. Also, GitLab, which is gaining plenty of traction these days, is only using "official" releases, therefore they are stuck at v1.10.1 from September. Some of their core team members and contributors also submitted bugfix PRs to Rouge, but they haven't been reviewed or merged so far.

To be absolutely clear: Absolutely no offense @jneen, I know how difficult it is to find time for maintaining code that is not one's primary work! Just to make sure there are no wrong expectations: Is there any chance you can have a look at some of the latest PRs and release a new version in the next weeks?

**Comment by alexdowad** [comment]
One maintainer doesn't scale. When a project gets popular, like this one, the author needs to find a couple of other contributors who understand the project's direction and care enough to maintain quality and give them commit rights.

Or if the sole maintainer just totally disappears, eventually someone else has to fork it and keep things moving forward.

**Comment by sraboy** [comment]
I definitely agree and wish the project could move faster. I'd also second @pbregener that this is not an indictment of @jneen, just a reality of the project. She's done a lot of great work but supporting a project like this in her off-time cannot be easy. 

I think some responsibility lies with GitHub as well. Adopting a small project like rouge on such a massive scale makes me feel like they could work with @jneen to request/offer to get a couple devs on the project with the ability to pull/merge, assuming she's willing.

**Comment by stanhu** [comment]
@pbregener @alexdowad @sraboy Thanks for bringing up this topic. I am extremely excited to announce that @jneen has started working full-time at GitLab for the next few months to improve Rouge. We'll be adding team members as we can to learn from her and help make this project even better. We're prioritizing certain issues right now (e.g. lexer bugs causing infinite loops, missing data, etc.), but please feel free to flag issues that you think need handling ASAP. Thanks for your patience!

**Comment by jneen** [comment]
Hi all. Thank you for your concern - I have been dealing with a cascade of major medical issues on top of working full-time, so in the last year or so rouge hasn't gotten the attention it deserves. But thanks to GitLab I can commit some paid time to digging this project out of the hole it's been in. This week I'm triaging issues and next week I should be able to cut a release.

**Comment by pbregener** [comment]
:tada:
