### ISSUE TITLE
Option of external source to syntax-highlight

### ISSUE THREAD

**Issue by ph-hs** [jneen/rouge#413]
Please excuse the Github-Pages Kramdown style, to outline what I'm suggesting:

> '''javascript
> ###RougeProcessorExternalFile=http://example.com/some.js
> '''

It'd be super cool, if Rouge could ingest files and highlight them at build-time, but do so from a HTTP source instead of a mandatory copy/paste as it is now. Obviously I've kludged back-ticks in the code sample above.

**Comment by jneen** [comment]
Hi @ph-hs. This is a feature for your blog or other system to implement, and is not within the purview of rouge.
