### ISSUE TITLE
Properties highlighting doesn't allow for hyphens (nor other non-\w chars) in keys.

### ISSUE THREAD

**Issue by twbecker** [jneen/rouge#419]
The properties lexer seems to only allow for word characters \w in property keys. Hyphens in particular mess up the highlighting.  According to the closest thing I could find to a [spec](http://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-):

_"The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator"_

**Comment by mnlipp** [comment]
Confirmed. It really looks strange if the key contains a hyphen. The part up to the hyphen gets style "err".

**Comment by jneen** [comment]
Hi @twbecker, thanks for the find. I'll look into it.

**Comment by cezariuszmarek** [comment]
Any hints where it should be corrected? Is it [this line](/jneen/rouge/blob/master/lib/rouge/lexers/properties.rb#L17)?
