### ISSUE TITLE
code blocks using ``` syntax not highlighted when in lists

### ISSUE THREAD

**Issue by Treri** [jneen/rouge#425]
I used rouge (1.10.1) in jekyll 3.0.3 (github pages used version) on OS X 10.11.3

###### What did you do?
use below content
```
1. list1
2. list2

    ```js
    var a = function(){}
    ````
```

###### What did you expect to see?
code blocks are highlighted correctly


###### What did you see instead?
code blocks are not detected and highlighted. just output 

```
<p>```js
var a = function(){}
```</p>
```

If I delete leading 4 space, it is highlighted correctly, but the code block will not be in the list item level anymore

**Comment by Treri** [comment]
Sorry, forget this issue 😰

**Comment by geraldb** [comment]
@Treri   FYI:  It's not a bug. If you use kramdown you have to "fix" your source e.g. ident the code block the same as the first non-list marker. See the [Jekyll F.A.Q ](https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md) entry titled "How can I get backtick fenced code blocks working inside lists (with kramdown)?".Cheers.
