### ISSUE TITLE
Swift lexer bug related to multiline comments

### ISSUE THREAD

**Issue by dblessing** [jneen/rouge#453]
Multiline comments don't seem to be parsed correctly in Rouge. See the following example:

```
/* 
<html://apple.com> text "with quotes no LF" 
*/

static func myFunc() { 
var string = "hello" 
return string 
}

/* 
<html://apple.com> text "with quotes 
and LF" 
*/ 

static func myFunc() { 
var string = "hello" 
return string 
} 
```

The first comment and function are correctly highlighted. However, the second function is not highlighted correctly due to the line feed in the comment. You can see how this works by putting the example in rouge.jneen.net.

**Comment by jneen** [comment]
Hi @dblessing, good catch! I've saved your snippet so we can refer to it later: http://rouge.jneen.net/pastes/M3EV

**Comment by dblessing** [comment]
I did some more testing. It seems that it's not the newline in the comment body that matters - it's the `<html://apple.com>` part. The slashes in there mess up the lexer.
