### ISSUE TITLE
Javascript highlight error if object property is quoted

### ISSUE THREAD

**Issue by yuloh** [jneen/rouge#459]
When using javascript syntax highlighting, if you define an object with a quoted property name _and_ the value is an object, the next property is highlighted as an error.

![Screenshot of highlighting error](https://cloud.githubusercontent.com/assets/9440455/14891683/a1cbf554-0d35-11e6-9472-ba6615ff5e5c.png)

If the property name is not quoted, or the value is not an object, it's fine.

http://rouge.jneen.net/pastes/K3OA

**Comment by jneen** [comment]
sigh. this part of the lexer seems to have no end of bugs. i'll take a look.

**Comment by nbering** [comment]
I'm seeing a similar issue. Not sure what version this is... whatever's bundled with github-pages gem right now. Hopefully this will help reproduce the issue. My case is a wee bit different, but has in common that the colons in an object literal appear as an error.

![image](https://cloud.githubusercontent.com/assets/4421371/15988695/f67bdafa-3027-11e6-9eb2-fba1535fd8bb.png)
