### ISSUE TITLE
My syntax highlighting isn't working

### ISSUE THREAD

**Issue by xDinomode** [jneen/rouge#465]
I'm using jekyll 3 and the config file has **markdown: kramdown** and **highlighter: rouge** but the syntax highlighting isn't the same. 

### Here's how it looks on my website 

> btw I downloaded some "syntax.css" file off the internet and using that on the site. Should I be?.. idk 

![my website](http://i.imgur.com/WH0vIAP.png)

### And here's how it looks on the Rouge website

![rouge](http://i.imgur.com/hvejUPi.png)

**Comment by jneen** [comment]
Hi @xDinomode, thanks for reaching out. I'm a little confused - it seems to be highlighted on your website, just in different colors. Is there a part of the text that isn't highlighted?

**Comment by xDinomode** [comment]
@jneen Ahh ok so this isn't a bug. Thanks!
