### ISSUE TITLE
How can I change the font?

### ISSUE THREAD

**Issue by Seybo** [jneen/rouge#470]
I'm putting font line in `rouge.css.erb` like this
```
<%= Rouge::Themes::ThankfulEyes.render(:scope => '.highlight') %>

.highlight {
  font-family: 'Roboto Slab', serif;
  font-size: 18px;
}
```

but it doesn't work. 

I have tried to put this block in my `custom.css` as well but still I can't change the font. 
At the same time I can change the other properties like the font size. But I still end up with the _Menlo font_.

How can I change it? 

This font is included in my `application.scss` and works all over the website
```
@import url(https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700);
$baseFontFamily: "Roboto Slab";
```

**Comment by jneen** [comment]
Hi @Seybo. Rouge themes do not output any css that imposes fonts (other than bold or italic) - I would take this up with the maintainers of whatever system you're using that uses rouge. As a hack I could suggest adding `!important` after each rule in your custom block, but that is clearly not optimal.
