### ISSUE TITLE
Highlights Ruby method calls the same as method definitions

### ISSUE THREAD

**Issue by janko-m** [jneen/rouge#471]
Thank you for this great pure-ruby alternative to pygments. The only difference that I've noticed when switching from pygments to Rouge is that now my method calls are highlighted the same as method definitions. I would prefer if method calls were the same neutral style as e.g. local variables.

<img width="419" alt="screen shot 2016-05-22 at 21 08 39" src="https://cloud.githubusercontent.com/assets/795488/15454112/668fc15c-2061-11e6-9fb1-44e3d69c7b82.png">

```rb
require "rouge"
source = <<-EOS
def method
end

foo.method
EOS
formatter = Rouge::Formatters::HTML.new
lexer = Rouge::Lexers::Ruby.new
puts formatter.format(lexer.lex(source))
```
```html
<pre class="highlight"><code><span class="k">def</span> <span class="nf">method</span>
<span class="k">end</span>

<span class="n">foo</span><span class="p">.</span><span class="nf">method</span>
</code></pre>
```

As you can see, both method definition and method call have the "nf" class.

**Comment by jneen** [comment]
Hi @janko-m. Unfortunately, I think this is more or less a matter of opinion - every highlighter will highlight languages slightly differently and make different choices. Our claim of pygments compatibility is on the formatter side - it *works* with the same stylesheets, but may choose to lex parts of the language differently.

**Comment by janko-m** [comment]
@jneen I would like to revisit this issue, I want to find out what is the advantage of having method calls preceeded with a dot are highlighted the same as method definitions? Could we have it colorless like the GitHub highlighter?

```rb
def method
end

foo.method
```

The current way isn't semantically consistent, because in the only explicit method calls will be higlighted, methods implicitly called on `self` will stay colorless (since lexer of course cannot know whether something is a variable or a method call). Could we fix this inconsistency by having both versions colorless?
