### ISSUE TITLE
Cannot use "Append" - Runtime error

### ISSUE THREAD

**Issue by mjclemente** [jneen/rouge#482]
I'm trying to put together a lexer, based off the javascript lexer.

Prepend is working without issue, as in the QML/Javascript example. However, when I try to follow the readme and append to the parent :root state, I get a runtime error: 
```
no such state ""
file: regex_lexer.rb location: append line: 196
```

I'm just doing a basic 

```
append :root do
    rule /"(\\\\|\\"|[^"])*"/, Str::Double
end
```
Any insight or help would be greatly appreciated. Thanks!

**Comment by jneen** [comment]
Oh no! This is definitely not intended behavior. Could you send over the source of your lexer, so we can reproduce it?

**Comment by mjclemente** [comment]
Here's a stripped down version that's throwing the error.

This file is rouge/lib/rouge/lexers/bugtest.rb:
```
module Rouge
  module Lexers
    load_lexer 'javascript.rb'

    class Bugtest < Javascript
      title "bugtest"
      desc 'Testing Append Bug'
      tag 'bugtest'
      aliases 'bugtest'
      filenames '*.bugtest'

      prepend :root do
        rule /(?:true|false|null)\b/, Keyword::Constant
      end

      append :root do
        rule /"(\\\\|\\"|[^"])*"/, Str::Double
      end

    end
  end
end
```
It corresponds to rouge/spec/visual/samples/bugtest (which, for testing, is just copied from the javascript same).

When I comment out the "append" block, it works, otherwise I get the error:

```
RuntimeError at /bugtest
no such state ""
file: regex_lexer.rb location: append line: 196 
```

I'm new to ruby, so I hope this isn't just a simple mistake on my part. Thanks for looking at it.

**Comment by jneen** [comment]
Welp, that would do it. @mjclemente, could you confirm that the above commit resolves your issue?

**Comment by mjclemente** [comment]
@jneen Working! Thank you so much!
