### ISSUE TITLE
Problems implementing Rouge in a fresh Rails 5 install

### ISSUE THREAD

**Issue by marcamillion** [jneen/rouge#488]
Not sure if this is related to Rails 5, but this is what I am facing. I have never used Rouge before, but I have used Pygments.rb.

This is what I have done.

Gemfile:

    gem 'rouge'
    gem 'redcarpet'

Then I created a `config/initializer/rouge.rb`:

    require 'rouge/plugins/redcarpet'

Then I created a file called `app/assets/stylesheets/rouge.css.erb`

    <%= Rouge::Themes::Github.render(:scope => '.highlight') %>

Then in my `app/helpers/application_helper.rb`, I added this:

    module ApplicationHelper
      class HTML < Redcarpet::Render::HTML
        include Rouge::Plugins::Redcarpet
    
        def block_code(code, language)
          Rouge.highlight(code, language || 'text', 'html')
        end
      end
    
      def markdown(text)
        render_options = {
          filter_html: true,
          hard_wrap: true,
          link_attributes: { rel: 'nofollow' }
        }
        renderer = HTML.new(render_options)
    
        extensions = {
          autolink: true,
          fenced_code_blocks: true,
          lax_spacing: true,
          no_intra_emphasis: true,
          strikethrough: true,
          superscript: true
        }
        Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
      end
    end

Then in my `show.html.erb`, I did this:

    <%= markdown(@question.body) %>

But that literally does not work. It outputs my `ruby` code snippet like this:

<img width="766" alt="unformatted-ruby-snippet" src="https://cloud.githubusercontent.com/assets/137772/15875428/70c78bd2-2ccd-11e6-9d30-6c8dfec1e45f.png">

How do I get this snippet of code to be formatted like Github? Or even just the first step being to be formatted any at all, then how do I tweak the formatting?

Or even when I do this:

                <div class="highlight">
                  <%= @question.test_suite %>
                </div>

It renders like this:

<img width="798" alt="unformatted-ruby-snippet-2" src="https://cloud.githubusercontent.com/assets/137772/15875453/86869346-2ccd-11e6-91de-2a6a8019d6ba.png">

Not quite sure about what I am doing wrong.

Ideas?

P.S. If you are interested in answering this on SO, [feel free to do so here](http://stackoverflow.com/questions/37668675/how-do-i-implement-rouge-syntax-highlighting-in-rails).

  [1]: http://i.stack.imgur.com/nKJd9.png
  [2]: http://i.stack.imgur.com/qQ49F.png

**Comment by jneen** [comment]
Hi, thanks for the report. Could you find the actual HTML and CSS being rendered and pastebin or gist them? I suspect the class names aren't lining up for some reason.

**Comment by marcamillion** [comment]
No prob @jneen. 

Here you go: https://gist.github.com/marcamillion/ddce2f675a0589e55819e6457b89b829

That's the HTML from two different code samples and the one stylesheet that is generated from the asset pipeline.

This is the name of the stylesheet: 

`http://localhost:3000/assets/rouge.self-664f0871aac8cdea8b195a62e3a68fcd16ed320ac0b24c439e099cbf856985b9.css?body=1`

**Comment by jneen** [comment]
Hm, interesting - it doesn't seem to be lexing it at all. Are you sure it's using the 'ruby' language and not defaulting it to 'text'?

**Comment by marcamillion** [comment]
I am not sure to be honest.

How do I test that manually?

I have been struggling with figuring out how to ensure it is doing that, to
be honest.

What's wrong in my code or what can I change to check?

On Wednesday, June 8, 2016, Jeanine Adkisson <notifications@github.com>
wrote:

> Hm, interesting - it doesn't seem to be lexing it at all. Are you sure
> it's using the 'ruby' language and not defaulting it to 'text'?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jneen/rouge/issues/488#issuecomment-224653300>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAIaLNyZrRkscciQdHv-voWQL7tbp1Q7ks5qJvIxgaJpZM4IwYmj>
> .
>


-- 
Marc Gayle
www.marcgayle.com
www.twitter.com/marcgayle

**Comment by jneen** [comment]
I'd put a `puts` or similar in that `block_code` method where you have `language || 'text'`. Or you could try changing that to `language || 'ruby'` and see if you suddenly get ruby ;)

**Comment by marcamillion** [comment]
@jneen If I just do `language || 'ruby'` I get a 'wrong number of arguments' error. If I do `language || 'ruby', 'html'` it still doesn't work.

I added a `binding.pry` to that block, and I see that `language` is nil. Where should I be manually setting language other than that `block_code` method?

**Comment by marcamillion** [comment]
For what it's worth, when I make the following changes:

In my `block_code` method, I call highlight as follows:

    Rouge.highlight(code, 'ruby', 'html')

Then in my view I do this:

```
<%= raw rouge_markdown(<<-'EOF'
                def rouge_me
                  puts "this is a #{'test'} for rouge"
                end
                EOF
                ) %>
```

Then that produces this:

<img width="783" alt="screen shot 2016-06-09 at 5 46 00 pm" src="https://cloud.githubusercontent.com/assets/137772/15949058/3e774cdc-2e6a-11e6-93b6-fff0dd575be5.png">

Note I am referring to the code snippet at the bottom.

However, the text at the top is generated with this:

              <pre class="highlight ruby">
                <%= rouge_markdown(@question.body) %>
              </pre>

And it is rendered as is shown in the screenshot.

**Comment by marcamillion** [comment]
Anything further on this @jneen?

**Comment by jneen** [comment]
Hi @marcamillion - I'm not sure I can debug this for you remotely. If you can come up with a minimal test case in a way I can use I'd be happy to look at it, but to me it looks like your markdown setup isn't properly passing languages through, which is beyond the scope of rouge.

**Comment by marcamillion** [comment]
Nevermind, I got a useful answer that helped me [solve it here](http://stackoverflow.com/a/37721539/91970).

**Comment by jneen** [comment]
Yay, I'm glad!

**Comment by F3PiX** [comment]
Is there news on this one? I can't get Rouge working with Rails 5.

**Comment by jneen** [comment]
Note that in Rouge 2.0, we no longer apply a `<div...>` wrapper, so you are responsible for putting the output in an appropriate context so that your stylesheet will style it, as well as in a `<pre...>` or a context with `white-space: pre`.

You will also have to do some backflips to prevent Rails from re-escaping the HTML that rouge outputs, using `raw` or `.html_safe` or similar.

**Comment by jneen** [comment]
Unfortunately, I don't have the bandwidth to help you drill down to a solution remotely. I suggest debugging this by:

* trying things out in the console (or `binding.pry`)
* inspecting the HTML output in your browser
* inspecting the CSS you're using, whether from a theme or stylesheet.

**Comment by F3PiX** [comment]
Hi Jneen, thank you for your suggestions.  I didn't find a solution yet. One last question: do you know of any Rails 5 app that got Rouge working? It would help to know if the problem is in my own code, not in Rails 5.
