### ISSUE TITLE
C/C++ syntax highlighting for *.C and *.H files

### ISSUE THREAD

**Issue by pasbec** [jneen/rouge#494]
Dear jneen,

I was encouraged by [Stan Hu](https://gitlab.com/u/stanhu) from GiLab to file an issue here, which relates to the corresponding issue #18387 on GitLab:

 [GitLab: C/C++ syntax highlighting for *.C and *.H files](https://gitlab.com/gitlab-org/gitlab-ce/issues/18387).

The very popular Fluid Dynamics library OpenFOAM and most of its forks rely on *.C and *.H files for both C and C++ code. See e.g.:

[GitHub: OpenFOAM-3.0.x](https://github.com/OpenFOAM/OpenFOAM-3.0.x/blob/master/src/OpenFOAM/db/IOobjects/IOField/IOField.H).

I'm hosting a fork of OpenFOAM in GitLab CE on my own private server. There, the syntax highlighting does not work (it is shown as plain text only). In order to demonstrate this, I have cloned a similar example to the official GitLab site, see e.g.:

[GitLib: foam-extend-3.2](https://gitlab.com/pasbec/foam-extend-3.2/blob/nextRelease/src/foam/db/IOobjects/IOField/IOField.H).

As far as I understood, GitLab uses Rouge for syntax highlighting. At least from having a quick look at some code of Rouge, I found that both lexers for C and C++

[Rouge lexer for C](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/c.rb)
[Rouge lexer for C++](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/cpp.rb),

are missing the file extensions *.C and *.H, even though they are officially regarded as valid file extensions - at least for gcc:

[gcc 4.9.3 manual - suffixes](https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Overall-Options.html#index-file-name-suffix-71)

The lexers for C++ additionally seem to miss the file extensions *.CPP and *.HPP.
An automatic detection / guessing of the correct language seems to fail, too. But I have only tested this by using GitLab.

Is this bug (or lets better say limitation) by intention? Is it possible for you to make the syntax highlighting work for these file extensions in rouge and GitLab?

Please let me know if I can help somewhere (e.g. for testing, etc.).

Best regards,
Pascal

**Comment by jneen** [comment]
Hi @pasbec, thanks for the well-written note.  Is the issue here merely casing? I think the plan is to make that glob-matching case-insensitive. If you want `*.C` files to be highlighted as C++, I'm proposing a way to make language selection user-configurable, since in the general case we'd want to highlight that as C.

**Comment by pasbec** [comment]
Hi @jneen, thanks for your quick reply.

To be be honest, I'm not the expert in language nomenclature and file extension definitions. But somehow I got the feeling that it is rather less about casing. If I understand the [gcc options](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html) correctly, and that's roughly the same as my perception was so far, then they mean the following:

*.c                                                           : C source code
*.h                                                           : C, C++, Objective-C or Objective-C++ header file
*.cc, *.cp, *.cxx, *.cpp, *.CPP, *.c++, *.C   : C++ source code
*.hh, *.hp, *.hxx, *.hpp, *.HPP, *.h++, *.H  : C++ header file

In case of OpenFOAM *.H and *.C file extensions are indeed used for C++, exactly as given by the gcc specs. In this regard, my selected title was probably somewhat misleading as I wrote C/C++ thinking of C syntax within C++ code.

According to the [suffix rules of GNU make ](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html), *.C (capital letter) is also referred to as C++ code, even though they encourage users to use *.cc.

The folks from Intel ([Intel C++ R User and Reference manual](http://www.physics.udel.edu/~bnikolic/QTTG/shared/docs/intel_c_user_and_reference_guide.pdf)), cf. page 40 (page 48 of the pdf), also define *.C (capital letter) files as C++ code.

Anyway, there seems to be some inconsistency, see e.g. in this [discussion](http://stackoverflow.com/questions/1545080/c-code-file-extension-cc-vs-cpp/1545085). But from comparing different specs, it would probably make more sense to regard the capital letter *.H and *.C suffixes as C++ code. Especially since all the tools close to GNU/Linux and UNIX treat them as such.

Any ideas?

**Comment by jneen** [comment]
Ah well there you go. That surprises me honestly, since I'd expect there to be no difference at all between `*.c` and `*.C` on e.g. windows or mac which have case-insensitive file names (although in slightly different senses).
