### ISSUE TITLE
Colons marked as errors in Javascript case statements

### ISSUE THREAD

**Issue by julioolvr** [jneen/rouge#497]
![image](https://cloud.githubusercontent.com/assets/1302493/16178720/a7826806-3626-11e6-8164-e815df703215.png)

Link: http://rouge.jneen.net/pastes/wZ91

I tried this on http://rouge.jneen.net/ which I assume uses the latest version of rouge. I've seen this happen on my blog with `middleman-syntax` but I can't tell exactly which version of rouge that runs.

I feel bad about reporting this one without a patch since a quick search through the issues in the repo brings up that colons in Javascript are a world of pain. I'll see if I can take a look at it soon and come up with a fix.

**Comment by jneen** [comment]
@julioolvr i think i fixed it - can you confirm this patch does the trick? i... just added a good ol catch-all at the bottom of `:root` for colons i'm afraid.

**Comment by julioolvr** [comment]
That seems to do the trick :) I gave a quick try at implementing the rules for the switch statement according to [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-switch-statement) but it was far from trivial (and that's without even considering that I have to learn the DSL). It seems like a fun weekend project though, trying to implement a small part of the grammar following the spec. Hopefully one of these days I'll send a PR with something.

Thanks!
