### ISSUE TITLE
Shell highlighting breaks on ANSI-C quotes (dollar-quotes)

### ISSUE THREAD

**Issue by okdana** [jneen/rouge#499]
I noticed this in GitLab, and i can reproduce it in the test thingie on the Rouge site: The shell highlighting breaks when it encounters ANSI-C quotes (aka dollar quotes). Specifically, it appears that it doesn't correctly terminate the quote. Test case:

```
#!/bin/bash
echo $'my dollar-quoted string'
echo 'This line is broken now'
exit 1 # So is this line
```

Output with dollar quotes versus regular single quotes:

![screen shot 2016-06-22 at 13 39 33](https://cloud.githubusercontent.com/assets/122095/16279065/f1cdc7c0-387e-11e6-8d46-baea4b220ebb.png)
![screen shot 2016-06-22 at 13 40 10](https://cloud.githubusercontent.com/assets/122095/16279069/f36ce21e-387e-11e6-8cc4-f1c9e7999494.png)

**Comment by jneen** [comment]
@okdana Looks like there was a bad regex that used `$` instead of `\$`. But I also added support for escaped chars in there while I was at it. Can you verify that the above commit fixes your case?

**Comment by okdana** [comment]
I'm not actually a Ruby developer myself so i don't really know what i'm doing with this. :/ However, i did manage to build it and use the `rackup` command to confirm that the line you added to the lexer test page seems to work, at least. Looks dope, thanks!

**Comment by jneen** [comment]
:D
