### ISSUE TITLE
Pascal/Delphi issues with highlighting - missing extensions

### ISSUE THREAD

**Issue by furai** [jneen/rouge#500]
Hey,

So I come from gitlab. Before the latest update of gitlab (8.9) I had manually modified rouge in my installation. I've added pascal/delphi highlighting to it based on the old pull request which is now merged in.

There was one problem with that applied fix. It didn't take into account all delphi/pascal file extensions.

`*.dpr, *.lpr, *.pp`

These are needed as well. I added those and all was good.

Now after upgrading to latest gitlab version everything went sideways. No syntax highlighting for Pascal/Delphi works. Even with *.pas files. I'm wondering what the issue is here.
There is slight chance that because I had it modified by hand in the past - during the update process it didn't update properly and something doesn't work so this issue is totally redundant.

Please let me know (if you know how to) get in gitlab the latest **FRESH** rouge version, so I can test it properly. We have huge project in Delphi/Pascal and I'd like to contribute to this project with needed fixes.

Cheers,
Furai

**Comment by jneen** [comment]
Hi! Running the *latest* version of rouge in gitlab is a bit complicated, since gitlab depends on gollum, which depends on rouge 1.x.

So my recommendation would be to edit the local project's Gemfile, specifically the "gollum-lib" and "rouge" entries:

``` ruby
gem 'rouge', git: 'https://github.com/jneen/rouge'
gem 'gollum-lib', git: 'https://github.com/gollum/gollum-lib'
```

Then run `bundle update rouge gollum-lib` and restart your server.

**Comment by jneen** [comment]
Unfortunately, we can't globally map `*.pp` to Pascal, since that's already associated with Puppet. But! I'm working on a GitLab feature that will let you manually set up highlighting preferences via `.gitattributes`: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4606. So you'd just add:

```
*.pp gitlab-language=pascal
```

to your `.gitattributes` file and you should get the behavior you want.

**Comment by jneen** [comment]
In the meanwhile, instead of editing files in gems, which will break every time a gem is updated, I recommend monkey-patching the Pascal highlighter in an initializer (say, `config/initializers/custom-pascal.rb`):

``` ruby
Rouge::Lexers::Pascal.filenames << '*.pp' << '*.dpr' << '*.lpr'
```

**Comment by furai** [comment]
That sounds good but still, in current gitlab installation the highlighting doesn't work at all even for .pas. How can I make sure that the gem is what it's supposed to be?

**Comment by jneen** [comment]
I'm not sure what you mean - if you installed gitlab, the gem should be what it's supposed to be? You can try `gem uninstall`ing the thing and then running `bundle` again to get a fresh copy?

**Comment by furai** [comment]
I mean that I had upgraded gitab from 8.8.2 to 8.9. My old version had been modified by me. And now I'm not entirely convinced that during the upgrade process the gem was updated cleanly. And if the issues I'm getting are my or rouge's fault.

I'll try what you just said to get it freshly installed and see if I still get same issues.

**Comment by furai** [comment]
http://file.furai.pl/2016-06-23_21-51-40.png << it looks like this for this .pas file

**Comment by furai** [comment]
Apparently that gem version dosen't even have pascal lexer.

**Comment by jneen** [comment]
Here's what I'm seeing - at v1.11.0, there is a pascal lexer, and `filname: 'foo.pas'` results in the Pascal guess.

```
[ jneen@pepper rouge ] -> (detached) $ 
; g l -1
* 7db5e04 (HEAD, tag: v1.11.0) v1.11.0

[ jneen@pepper rouge ] -> (detached) $ 
; b pry -r./lib/rouge.rb
[1] pry(main)> Rouge::Lexer.guess(filename: 'foo.pas')
=> Rouge::Lexers::Pascal
```

**Comment by jneen** [comment]
could you try running the following, in `./bin/rails console`:

```
Rouge::Lexer.guesses(filename: 'foo.pas')
```

and pasting the output here?

**Comment by jneen** [comment]
Okay, never mind that. It looks like this was a release bug for rouge 1.11.0 - somehow the pascal lexer didn't get included, despite it being present in the git tree (?)

**Comment by jneen** [comment]
So my recommendation, from a purely rouge standpoint, is to upgrade to 1.11.1. I'll move back to the gitlab thread for how we're going to deal with the gitlab-specific issues.

**Comment by furai** [comment]
Thanks for support.
