### ISSUE TITLE
java literal underscore highlighting

### ISSUE THREAD

**Issue by vandiedakaf** [jneen/rouge#502]
Java literals with underscores, http://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html, are not highlighted correctly.

See example http://rouge.jneen.net/pastes/jmE5

I expect the entire literal to be of the same colour.

Regards
-f

**Comment by jneen** [comment]
Hi @vandiedakaf! Good catch. Could you confirm that the above works for you?

**Comment by vandiedakaf** [comment]
Hi @jneen 

Thanks for the speedy response.

I've made my **first** git pull request: https://github.com/jneen/rouge/pull/503

You'll notice that your latest build is failing -- I could not figure out why that is (other than it was the new Java changes that made it fail).
