### ISSUE TITLE
TypeScript React support

### ISSUE THREAD

**Issue by janslow** [jneen/rouge#516]
It would be great if rouge supported [TypeScript React](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html) syntax (`*.tsx` files). 

For example:

``` tsx
const x: number = 2;
return <div>{x}</div>;
```

I expect this is probably blocked on #275 / #336, as TSX is a combination of JSX and TS.

**Comment by RinatMullayanov** [comment]
+1 very lack of support
