### ISSUE TITLE
Add syntax highlighting for *.cljc and *.boot (same as clj and cljs) 

### ISSUE THREAD

**Issue by kennyjwilli** [jneen/rouge#520]
The syntax highlighting for `*.cljc` and `*.boot` files should be the same as `clj` and `cljs`.

**Comment by jneen** [comment]
I believe we do support `.cljc`? And I'm a little wary to add `.boot` (not a fan of libraries creating their own extensions for the same kind of code)... buuuut I'd merge it, and keep it around until it conflicts with something.

**Comment by kennyjwilli** [comment]
You're right about cljc, I guess I must have been using an old version or something. Understandable about `.boot`. They are using their own extension because it `require`s some functions from boot by default without having an explicit `require`.

**Comment by pandeiro** [comment]
I've added `build.boot` to the clojure filenames since the entire filename is the convention used by the [Boot build tool](https://github.com/boot-clj/boot) and would not conflict with other possible uses of the `.boot` extension.
