### ISSUE TITLE
Elixir parser is a bit too greedy when parsing regex

### ISSUE THREAD

**Issue by mhelmetag** [jneen/rouge#528]
The Elixir parser doesn't seem to close regex highlighting correctly.

As seen in this screenshot (sorry... mobile):
![screenshot_20160811-231547](https://cloud.githubusercontent.com/assets/8609429/17614266/c67cb7b2-6019-11e6-9162-80dd2ec4e793.png)

Also seen in this [issue](https://github.com/exercism/exercism.io/issues/3031).

**Comment by Insti** [comment]
Here's the relevant code snippet in copy/pasteable format.
```
    string |> String.split(~r/[ -]/) |> Enum.map(&abbreviate_word/1) |> Enum.join()
```

**Comment by Insti** [comment]
https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/elixir.rb#L49

Would this fix it?

```        
rule %r{~r\/.*?\/}, Str::Regex
```

**Comment by k3rni** [comment]
Using a verbose regex for clarity:

```ruby
/~r
  ( / # opening slash, then
    (
      \\\/ # either an escaped slash
      | # or
      [^/] # any non-slash character
    )* # any number of times
  / ) # closing slash
/x

# or more plainly
%r{~r(/(\\\/|[^/])*/)}
```

See http://www.regexpal.com/?fam=95517 for a "testsuite".

However, this needs to take into account that Elixir sigils (which is what the tilde constructs are named, regex being only one of them) can use one of four different same-character delimiters: `/` `|` `"` `'` and four kinds of parentheses: `()` `[]` `{}` `<>` (see [Sigils](http://elixir-lang.org/getting-started/sigils.html)). 

It's easy to do for the single-character ones, but **strictly correct** matching of pairs of parentheses is impossible in regex. But I think that in this case, matching an escaped closing character or any non-closing one should be enough.

**Comment by Insti** [comment]
As long as your regex doesn't end with a backslash you're ok:
`String.split(~r/hello followed by a backslash\\/) |> Enum.map(&abbreviate_word/1)`

**Comment by k3rni** [comment]
This case can be handled by including an escaped backlash directly in the alternatives list: `/~r(\/(\\\\|\\\/|[^\/])*\/)/`

**Comment by mhelmetag** [comment]
I took a look at a [atom elixir langauge pack](https://github.com/elixir-lang/language-elixir/blob/master/grammars/elixir.cson#L146-L449) (more specifically the regex section) and it might be worth basing it around those rules.

**Comment by Insti** [comment]
@k3rni will make a PR?

**Comment by jneen** [comment]
Thanks all for your work! Hopefully we can get #530 merged soon.

**Comment by Insti** [comment]
#530 seems to have been merged, but the problem is still present on http://rouge.jneen.net/
```
    string |> String.split(~r/[ -]/) |> Enum.map(&abbreviate_word/1) |> Enum.join()
```

(`|> Enum.map(&abbreviate_word` should not be green)

Does the problem still exist or is the demonstration site out of date?

**Comment by mhelmetag** [comment]
I actually think this is good now. So I think we're okay to close.

<img width="1229" alt="screen shot 2017-09-16 at 1 49 30 pm" src="https://user-images.githubusercontent.com/8609429/30515917-e65abb30-9ae5-11e7-8a3b-316082c714d9.png">

**Comment by bu6n** [comment]
Sorry for responding to this old thread. I'm using gitlab with an elixir project and I often times come accross some inconsistencies with regexes, like this one:
`reg =  ~r/^folder_[^\/]+\/subfolder_[^\/]+$/`
This is for parsing the output of an S3 listing, so this is quite common I would say.

Here is how it currently looks like:

<img width="595" height="120" alt="Image" src="https://github.com/user-attachments/assets/bbcda301-78ab-4d9a-a421-09ac06404937" />
