### ISSUE TITLE
Syntax error in the biml lexer

### ISSUE THREAD

**Issue by skx** [jneen/rouge#538]
We're running biml indirectly, via `gollum`, and we see the following error when running with ruby 1.9.3:

      /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexer.rb:362:in `load': /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexers/biml.rb:16: syntax error, unexpected $undefined (SyntaxError)
              rule %r(<#@\s*)m, Name::Tag, :directive_tag
                         ^
      /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexers/biml.rb:16: syntax error, unexpected '\n', expecting tCOLON2 or '[' or '.'
      	from /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexer.rb:362:in `load_lexer'
      	from /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge.rb:57:in `block in <top (required)>'
      	from /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge.rb:56:in `each'
      	from /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge.rb:56:in `<top (required)>'

The same error also appears when running the example code directly.

      $ cat test.rb
      #!/usr/bin/ruby
      $:.unshift "/opt/gollum/gems/gems/rouge-2.0.5/lib/"
      require 'rouge'
      source = File.read('/home/steve/.bashrc')
      formatter = Rouge::Formatters::HTML.new
      lexer = Rouge::Lexers::Shell.new
      formatter.format(lexer.lex(source))
      print Rouge::Themes::Base16.mode(:light).render(scope: '.highlight')

      $ ruby test.rb
      /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexer.rb:362:in `load': /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexers/biml.rb:16: syntax error, unexpected $undefined (SyntaxError)
        rule %r(<#@\s*)m, Name::Tag, :directive_tag
                   ^
        /opt/gollum/gems/gems/rouge-2.0.5/lib/rouge/lexers/biml.rb:16: syntax error, unexpected '\n', expecting tCOLON2 or '[' or '.'

Running the same code under Ruby 2.x works correctly, which suggests that this is a ruby versioning problem.  So far two solutions have been found:

* Comment out the line which is affected in `biml.rb`.
* Escape the `@` symbol, thusly:
     *  `rule %r(<#\@\s*)m, Name::Tag, :directive_tag`

I'm not 100% sure if the latter solution is correct or valid, but since we're not attempting to show any biml files it works for us.

**Comment by jneen** [comment]
Aw, dang, okay, that looks like a bug. I believe I've fixed this for BIML in 2cdf15c - let me know if this is a problem with any other parts of the code.

**Comment by skx** [comment]
I can confirm escaping the `@` symbols resolves the problem.

Thanks for your prompt attention.  I'll hope for a new release soon, but for the moment we can patch in-place :)
