### ISSUE TITLE
Python: Does not recognize backslashes in raw strings in default parameters

### ISSUE THREAD

**Issue by pgacv2** [jneen/rouge#543]
The version of rouge on the project home page (http://rouge.jneen.net/) does not recognize the following Python code:

```
def x(y=r'\sdf\u0004'):
  print(y)
```

The backslashes are incorrectly highlighted:

![image](https://cloud.githubusercontent.com/assets/2688600/18589066/fb8d0b52-7bf6-11e6-88af-6964d1ec2208.png)

**Comment by jneen** [comment]
Hi! The website does need an update. This was fixed in 2724e35.
