### ISSUE TITLE
VimL Comment mistake

### ISSUE THREAD

**Issue by mueller-ma** [jneen/rouge#551]
When `"` is used in a `map` command in vimrc or similar files, it is recognized as a comment, but VIM won't take that as comment.
See line 15: https://github.com/mueller-ma/vim-config/blob/master/vimrc

**Comment by jneen** [comment]
Hi @mueller-ma - I'm not able to reproduce this in Rouge. If you're referring to the mis-highlight on Github itself, be aware that Github does not use Rouge for its highlighting.

Thanks!

**Comment by mueller-ma** [comment]
@jneen Hi,
I'm sorry, I had wrong information about the highlighter github is using.
