### ISSUE TITLE
Clojure: trailing comment highlighted incorrectly

### ISSUE THREAD

**Issue by daveho** [jneen/rouge#553]
For some reason, trailing Clojure comments are not highlighted as comments.

Example: http://rouge.jneen.net/pastes/llx4

I would have expected the "; => 5.0" part to be highlighted as a comment.

If there is a non-comment construct after the comment (i.e., the comment is not a trailing comment), then it is handled correctly: http://rouge.jneen.net/pastes/9NZ3

**Comment by jneen** [comment]
Hi, thanks for the report! I believe I've just fixed this in 879a8fd, could you confirm?

**Comment by daveho** [comment]
Awesome --- let me work on setting up a ruby environment so I can test your fix.  (I noticed the problem in jekyll and github pages.)

**Comment by daveho** [comment]
I've tested using the HTML formatter and the comment in my original example is marked as class "c1", which as far as I can tell is correct for a single line comment.  Thanks a lot!  (And thanks for rouge!)

**Comment by jneen** [comment]
Yay, thank you <3
