### ISSUE TITLE
ECMAScript/Typescript decorators highlighted as errors

### ISSUE THREAD

**Issue by johan13** [jneen/rouge#556]
The following code is valid Typescript from Angular 2's quick start guide:

``` typescript
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: '<h1>My First Angular App</h1>'
})
export class AppComponent { }
```

When highlighted with Rouge the `@` is highlighted as an error:
<img width="416" alt="screen shot 2016-10-26 at 00 31 14" src="https://cloud.githubusercontent.com/assets/643284/19706708/af9d3f6e-9b13-11e6-9110-184677f77452.png">

Decorators are currently in stage 2 of ECMAScript's TC39 process and for Typescript decorators are "experimental", but the Angular 2 makes heavy use of them already. Given Angular 2's popularity I think it would be a good idea to allow decorators in Rouge.

**Comment by jneen** [comment]
Hi! Thanks for the suggestion - I believe I've added support in 0d21c54.
