### ISSUE TITLE
Rust: `?` operator highlighted incorrectly

### ISSUE THREAD

**Issue by mkpankov** [jneen/rouge#566]
From my Jekyll-based site:

![screenshot from 2016-11-11 11 12 19](https://cloud.githubusercontent.com/assets/393741/20208526/ce48ea50-a7ff-11e6-8d1a-32a078ee6b84.png)

I'd expect it to be colored the same as other operators. Or maybe just bold black.

**Comment by jneen** [comment]
Yep, that's a bug. I think I've fixed it in c3537dd - could you confirm?

**Comment by jneen** [comment]
Closing as the above was released in v2.0.7.
