### ISSUE TITLE
Syntax highlighting for vue files

### ISSUE THREAD

**Issue by szachara** [jneen/rouge#573]
Vue files are single file components, in this files is html, javascript and css. For start the HTML syntax highlighter would be enough. 

Here are docs for vue files and how this files are structured:
https://vuejs.org/v2/guide/single-file-components.html

**Comment by jneen** [comment]
Interesting timing - I've just merged support for these: https://github.com/jneen/rouge/commit/dfc19b0ba8dbf358cc2e18634c4a17f5def5520a

**Comment by jneen** [comment]
Should be out in the next release.

**Comment by szachara** [comment]
:-D great, really funny and quick fix, thx
