### ISSUE TITLE
Shell script: incorrect parsing of number sign (#) when used as arithmetic base symbol

### ISSUE THREAD

**Issue by aucuparia** [jneen/rouge#574]
In shell scripts, a number can be interpreted as being in a certain arithmetic base using this syntax: `$((base#number))`. For example, `$((16#0F))` evaluates to 15.

However, Rouge interprets the number sign as the start of a comment.

I found this problem while using Jekyll and I've verified it at http://rouge.jneen.net/.

**Comment by jneen** [comment]
Hi! I think I've fixed this in e131e2d, could you confirm?

**Comment by oliver117** [comment]
Confirmed in ec665bb2cca
