### ISSUE TITLE
OCaml: leading backtick indicating polymorphic variant isn't recognized

### ISSUE THREAD

**Issue by gaborigloi** [jneen/rouge#581]
The leading backtick is highlighted in red, but it is valid OCaml syntax:
![screenshot_2016-11-29_14-52-10](https://cloud.githubusercontent.com/assets/10549240/20714284/6e62ae30-b643-11e6-98b3-f51036456764.png)
http://rouge.jneen.net/pastes/v82w

Could be highlighted as:
```OCaml
let ok = `Ok;;
```

**Comment by jneen** [comment]
Hi, thanks for the report! I believe I've fixed this in 8975a02, can you confirm?

**Comment by gaborigloi** [comment]
Thanks for the fix, I've tested it by changing `lib/rouge/demos/ocaml` and running `rackup`, and now it highlights polymorphic variants correctly :).
