### ISSUE TITLE
Syntax highlighting for script-tag in ERB-file

### ISSUE THREAD

**Issue by AlexWayfer** [jneen/rouge#582]
### Summary

I don't understand why `<% %>` (or `<%=`) make all before JavaScript code in `<script>` red (`.err`).

### Steps to reproduce

1. Create `.erb`-file
2. File must contain `<script>`
3. ERB-tags (`<% %>`) inside `<script>`

### Expected behavior

No problems, no errors (maybe warnings? but I don't think so).

### Actual behavior

JavaScript code between start (`<script>`) and first ERB-tag (`<%`) highlighted as wrong by CSS-class `.err`.

### Relevant logs and/or screenshots

[Just public snippet](https://gitlab.com/snippets/32741)
[And screenshot of this](https://gitlab.com/gitlab-org/gitlab-ce/uploads/59ba23f10c1e9b2286f1acb21d11fc89/image.png) (for record).

### Possible fixes

I don't know :(

**Comment by jneen** [comment]
Hi, good catch! It was a subtle issue where the HTML lexer was delegating in chunks that were too large to be broken apart by ERB. I think I've fixed it in 43fbbfc, could you confirm?

**Comment by AlexWayfer** [comment]
Yep! `master` version works good with it.

I can close issue, I guess.

Thank you very much.
