### ISSUE TITLE
How to :pop! multiple stacks

### ISSUE THREAD

**Issue by somiaj** [jneen/rouge#585]
I'm writing a lexer and at one point I need to pop 2 stacks on one trigger. I'm new to ruby so I'm still trying to figure out what everything does but looking though lib/rouge/regex_lexer.rb I notice that there is when :pop! that is used to pop a single stack and using this works just fine.

What I need to do is way to pop 2 (or ideally a variable number and maybe even pop back to root stack) ability for my lexer. I notice that there is a function

````ruby
    def pop!(times=1)
      raise 'empty stack!' if stack.empty?

      puts "    popping stack: #{times}" if @debug

      stack.pop(times)

      nil
    end
````

but I'm unsure how to use this to pop multiple states within my own lexer. It seems that this is a function and to use it I would have to write another option such as when :pop!! that would do two states or is there a way to call this directly within my lexer?

Thanks for your help,

jaimos

**Comment by jneen** [comment]
Hi Jaimos!

It looks to me like what you want are block actions. From within the block you can call any method on the lexer, including `pop!`, as many times as you want. For example:

``` ruby
state :my_cool_state do
  rule /something/ do
    token SomeToken
    push :some_state
    pop! 2
  end
end
```

**Comment by somiaj** [comment]
Thank you, that was what I was needing. I thought it was possible but couldn't figure out the correct syntax.
