### ISSUE TITLE
Different color for constants in Ruby

### ISSUE THREAD

**Issue by bluegod** [jneen/rouge#592]
Example:

```plain
class Random
  RANDOM_VAR = 1
  RANDOM_2 = 2
  RANDOM_3 = 3
end
```

Highlights as:

![screen shot 2016-12-15 at 15 37 31](https://cloud.githubusercontent.com/assets/999323/21227990/6de6dff8-c2dc-11e6-8f79-073c28b11949.png)

Using `rouge 2.0`

**Comment by jneen** [comment]
Hi! I've just fixed this in a0549d0. Thanks!
