### ISSUE TITLE
Syntax highlighting for templated tag in ERB-file

### ISSUE THREAD

**Issue by AlexWayfer** [jneen/rouge#593]
### Summary

I don't understand why `<% %>` (or `<%=`) at the beginning of HTML-tag make `<` of HTML-tag red (`.err`).

### Steps to reproduce

1. Create `.erb`-file
2. File must contain `<% %>` in `< >` (tag)

### Expected behavior

No problems, no errors (maybe warnings? but I don't think so).

### Actual behavior

`<` highlighted as wrong by CSS-class `.err`.

### Relevant logs and/or screenshots

[Just public snippet](https://gitlab.com/snippets/33741)
[And screenshot of this](https://cloud.githubusercontent.com/assets/6510020/21296647/a65b308a-c581-11e6-89e8-79805939093b.png) (for record).

### Possible fixes

I don't know :(

**Comment by jneen** [comment]
Hi there! This... sigh. I mean in a sense it's a potential error because `<>` isn't valid HTML. The HTML regex looks for `/<\w+/` for an open tag, which isn't matched here. It could be fixed by breaking those up into separate matches I suppose.

**Comment by AlexWayfer** [comment]
Thank you! Sorry for non-trivial issues 😅

You are very cool! 👏
