### ISSUE TITLE
JavaScript: Fails with parsing after newline padded expressions template literals

### ISSUE THREAD

**Issue by runarberg** [jneen/rouge#602]
First reported [here](https://gitlab.com/gitlab-org/gitlab-ee/issues/1473)

### Summary

JavaScript syntax highlighting fails when it encounters a newline inside an expression inside a template literal. After which it will reverse strings.

### Steps to reproduce

The following code snippet will be wrongly highlighted:

```js
const foo = 42;
const templateLiteral = `foo "${
  foo
}"`;

const bar = "bar";
const baz = "baz";
```

### Expected behavior

Syntax highlighting should work as expected.

In particular, the HTML for the last line of the snippet should be:
```html
<span id="LC7" class="line">
  <span class="kr">const</span>
  <span class="nx">baz</span>
  <span class="o">=</span>
  <span class="s2">"baz"</span>
  <span class="p">";</span>
</span>
```

where a class with `kr` is keyword highlighted, `s2` as a string, `nx` identifier, `o` as an operator, and `p` as punctuation.

### Actual behavior

The parts after the template literal have reversed highlighting for double quotes.

In particular, the HTML for the last line of the snippet is:

```html
<span id="LC7" class="line">
  <span class="s2">const baz = "</span>
  <span class="nx">baz</span>
  <span class="err">"</span>
  <span class="p">;</span>
</span>
```

### Relevant logs and/or screenshots

![Sample failure](https://cloud.githubusercontent.com/assets/3984600/21574663/c5e980b8-ceab-11e6-8778-5d07e40b46ae.png "Sample failure")

**Comment by dblessing** [comment]
The example you gave looks OK in the latest Rouge:

![screen shot 2017-01-04 at 3 46 26 pm](https://cloud.githubusercontent.com/assets/2394772/21660460/0aa5c58a-d295-11e6-83a4-0a97354bc16c.png)

It looks like this was fixed in https://github.com/jneen/rouge/pull/570 (Issue: https://github.com/jneen/rouge/issues/569). The next Rouge release will have this fix.

**Comment by jneen** [comment]
Closed as fixed for the next release. Thanks for the report!
