### ISSUE TITLE
PHP and Unicode variable names

### ISSUE THREAD

**Issue by Zefling** [jneen/rouge#621]
Code example on rosettacode.org for [PHP](https://rosettacode.org/wiki/Unicode_variable_names#PHP) has a strange result. The Unicode characters are in red. 

![rouge_php_unicode](https://cloud.githubusercontent.com/assets/3032555/22573766/c9cf86a4-e9aa-11e6-98f1-138c03511996.png)

**Comment by jneen** [comment]
Fixed in 9af4ac2f3a70c0223454a98464541735f5c7ad6d. Thanks for the report!
