### ISSUE TITLE
Hide syntax errors

### ISSUE THREAD

**Issue by tanrax** [jneen/rouge#624]
![image](https://sc-cdn.scaleengine.net/i/a9ae051d9ff6ebf61e4277977fe83df4.png)

The errors should not be displayed in red.

**Comment by jneen** [comment]
I'm confused about what you want to do. If you just want to ignore syntax errors globally, you can do that by modifying your CSS file's styling of them. If you want to use JSX syntax, you can use the `jsx` lexer.
