### ISSUE TITLE
In shell_session, comments using # are highlighted

### ISSUE THREAD

**Issue by natejgardner** [jneen/rouge#636]
The first word in bash/sh/zsh etc. comments is highlighted. E.g.:

```bash
# This line echoes stuff
$ echo 'Come to me in the silence of the night; come in the speaking silence of a dream.'
```

`This` is highlighted, where that entire line should be light grey.

![image](https://cloud.githubusercontent.com/assets/8813777/23975511/71f34236-099e-11e7-9624-de3a9af3d1b7.png)

**Comment by jneen** [comment]
Hi! The reason this was happening was that `#` is a common root prompt.

But I did work on this today. The original `shell_session` lexer was super lacking, and I've replaced it with a new `console` lexer (aliased for backcompat). It highlights comments as comments by default, unless the `?root=1` option is supplied, in which case it treats an initial `#` like a prompt.

**Comment by jneen** [comment]
(This has been changed so that the old behavior is the default, and you can enable toplevel comments with the `?comments=1` option.)

**Comment by jneen** [comment]
(You can also work around this immediately by using e.g. `##` for comments - as they will be highlighted as comments by the shell lexer.)
