### ISSUE TITLE
Support for diff + other language syntax highlighting 

### ISSUE THREAD

**Issue by revathskumar** [jneen/rouge#642]
Is it possible to have diff highlighting along with other syntax highlighting? 
Similar to this

![diff-with-code-highlighting](https://cloud.githubusercontent.com/assets/463904/24398546/79db8692-13c7-11e7-95d0-e1cdd8525ace.png)

**[EDIT]**

As of now it can highlight the code either as `diff` or as `json`, not able to combine both. If I use only diff then the output will be only diff highlighting without any syntax highligting of JSON.

![rogue-diff](https://cloud.githubusercontent.com/assets/463904/24402178/075ff9c8-13d5-11e7-9d12-f590045cff5d.png)

if not possible now, any plan to implement this in future?

**Comment by revathskumar** [comment]
It seems like a cutom json lexer with Diff rule will work.

```ruby
module Rouge
  module Lexers
    load_lexer 'json.rb'

    class JSONDiff < JSON
      prepend :root do
        rule(/^\+.*$\n?/, Generic::Inserted)
        rule(/^-+.*$\n?/, Generic::Deleted)
        rule(/^!.*$\n?/, Generic::Strong)
        rule(/^@.*$\n?/, Generic::Subheading)
        rule(/^([Ii]ndex|diff).*$\n?/, Generic::Heading)
        rule(/^=.*$\n?/, Generic::Heading)
      end
    end
  end
end
```

Hence closing the issue.

**Comment by revathskumar** [comment]
[revathskumar/rouge-json-diff-lexer-example](https://github.com/revathskumar/rouge-json-diff-lexer-example)

**Comment by BigChief45** [comment]
@revathskumar

Is there any way we can include this functionality in a PR so that it can be used out of the box in Rouge?

**Comment by gfx** [comment]
This is interesting for me.

**Comment by BigChief45** [comment]
@gfx Is there any way to give support for this? I'm open to design ideas, as I am getting familiar with the Rouge codebase.
