### ISSUE TITLE
Support for Clojure EDN data files

### ISSUE THREAD

**Issue by royaldark** [jneen/rouge#649]
It would be great if Rouge supported highlighting Clojure EDN (Extensible Data Notation) files (`.edn`). EDN is somewhat analogous to the relationship between JavaScript and JSON: it's a data specification format which for the most part "looks" and "acts" like standard Clojure data structures.

For example, you can define a map in a Clojure (code) file:
```clj
(def some-kinda-map
  {:age 18
   :name "John Doe"
   :siblings ["Jane Doe", "Jacob Doe"]})
```

The same map could be defined in a separate data-only EDN file, if desired:

```clj
{:age 18
 :name "John Doe"
 :siblings ["Jane Doe", "Jacob Doe"]}
```

The specification is well-defined and relatively simple: https://github.com/edn-format/edn

Given the high degree of overlap between plain Clojure and EDN, I'm guessing much of the existing Clojure highlighting code could be reused.

**Comment by jneen** [comment]
For now, I'll associate `*.edn` with the clojure lexer. If you think there's a compelling reason for a separate lexer, I'd be happy to look at a pull request for it :]

**Comment by royaldark** [comment]
The Clojure lexer seems to be working just great for EDN highlighting! Thanks for the update!
