### ISSUE TITLE
sed syntax highlighting deletes text from output

### ISSUE THREAD

**Issue by flxjander** [jneen/rouge#654]
Given the following source file "foo.sed":
```
/hello/p
```

Running `rougify highlight foo.sed` gives the following output:
```
/o/p
```

**Comment by flxjander** [comment]
See also: https://gitlab.com/gitlab-org/gitlab-ce/issues/30740
which is how I discovered the bug.

**Comment by flxjander** [comment]
Looks like 1bd4322cfcac620aaf16d04279b54be92e39a66b fixed it.  Thanks!

**Comment by gfx** [comment]
👍
