### ISSUE TITLE
Line feed between </table> and </code> complicates styling when chaining HTMLTable and HTMLPygments formatters

### ISSUE THREAD

**Issue by gpakosz** [jneen/rouge#658]
Hello,

When either using the `HTMLLegacy` formatter or when chaining formatters myself, the fact that the `HTMLTable` formatter **always** output a line-feed after the `</table>` tag introduces bottom "padding" difficult to remove with CSS.

[`html_table.rb:57`](https://github.com/jneen/rouge/blob/4f8af3c734e36b26744bee231ec2add832946964/lib/rouge/formatters/html_table.rb#L57)
```
yield "</tr></tbody></table>\n"
```

I don't know whether it's important for the `HTMLTable` formatter to output that ending line-feed and whether anything relies on it. I see two possible outcome to this issue since the `HTMLTable` formatter itself can't know whether it's the `inner` formatter of something else:

1. always prevent `HTMLTable` from outputting a line-feed:
```
yield "</tr></tbody></table>"
```
2. make `HTMLPygments` remove the "inner line-feed" before wrapping with `<pre><code>` and `</code></pre>`

I believe solution 1. is the way to go.

**Comment by jneen** [comment]
I'd actually prefer 2. here - a simple `strip` would solve it. Although I was under the impression that `<pre>` tags ignored trailing newlines?

**Comment by gpakosz** [comment]
Well chaining the two formatters gives `<pre><code><table>...</table>\n</code></pre>`

**Comment by gpakosz** [comment]
The following debug code:
```
      $stderr.puts '---'
      $stderr.puts 'language:' + language
      lexer = Rouge::Lexer.find_fancy(language, code) || Rouge::Lexers::PlainText
      $stderr.puts '---'
      $stderr.puts code
      $stderr.puts '---'
      s = formatter.format(lexer.lex(code))
      $stderr.puts s
      $stderr.puts '---'
```

outputs:
```
---
language:html
---
<div id='editor' ></div>
---
<pre class="highlight"><code><table class="highlight-table"><tbody><tr><td class="highlight-gutter gl"><pre class="lineno">1
</pre></td><td class="highlight-code"><pre><span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">'editor'</span> <span class="nt">&gt;&lt;/div&gt;</span></pr
e></td></tr></tbody></table>
</code></pre>
---
```

and here is the rendered html:
![image](https://cloud.githubusercontent.com/assets/553208/25152564/a18abb40-2489-11e7-9a85-de35bed4ecfa.png)

And now if I remove the `\n` between `</table>` and `</code></pre>` (either with browser devtools or straight from the html):
![image](https://cloud.githubusercontent.com/assets/553208/25152604/ce0e1518-2489-11e7-9a9e-fb39ae20ba45.png)

**Comment by gpakosz** [comment]
It's actually a bit more subtle. It's not only the `\n` the whitespaces inserted for indentation purposes before `</code></pre>` when injecting the produced fragment in a page that causes the massive trailing gap.

**Comment by gpakosz** [comment]
BTW, about 2.

Correct me if I'm wrong but by design of the `#stream()` yielding to `{ |piece| out << piece }` means it's too late to `#strip()` since `\n` has already been inserted to `out`.

**Comment by gpakosz** [comment]
Now that I think about it, `<table>` is not allowed within `<pre>` or `<code>` to begin with so the whole idea of `HTMLLegacy` wrapping `HTMLTable` within `HTMLPygments` is debatable.

What do you think?
