### ISSUE TITLE
Support Terraform configuration syntax

### ISSUE THREAD

**Issue by tsigo** [jneen/rouge#666]
The GitLab infrastructure team has recently started doing provisioning using [Terraform](https://www.terraform.io/), and it'd be great to have the configuration files highlighted.

[Here's an example of how we're using it](https://gitlab.com/gitlab-com/gitlab-com-infrastructure/merge_requests/8/diffs), and [here's the syntax documentation](https://www.terraform.io/docs/configuration/syntax.html).

**Comment by dblessing** [comment]
AFAIK, Terraform syntax is simply HCL. To keep the request more generic, let's use this issue https://github.com/jneen/rouge/issues/722. @tsigo If I'm wrong about this, let me know.
