### ISSUE TITLE
OCaml: identifiers beginning with underscore parsed incorrectly

### ISSUE THREAD

**Issue by gaborigloi** [jneen/rouge#671]
In case of identifiers beginning with `_`, the `_` is parsed as an operator, and not as part of the identifier:

![screenshot - 060517 - 10 47 17](https://cloud.githubusercontent.com/assets/10549240/25781877/3c4f27fe-3337-11e7-8bc0-7081d86bcf05.png)

**Comment by gaborigloi** [comment]
In fact, the OCaml manual says that the underscore `_` cannot be part of an operator: https://caml.inria.fr/pub/docs/manual-caml-light/node4.9.html

**Comment by emillon** [comment]
FYI, I included a fix for this one in #643.

**Comment by gaborigloi** [comment]
@emillon Thanks a lot for fixing this issue! :)
