### ISSUE TITLE
JSON object keys rendered as string starting with 2.0.6

### ISSUE THREAD

**Issue by sergionalin** [jneen/rouge#675]
Hi, I'm using Slate to write API docs, which in turn uses middleman w/ rouge.

With rouge 2.0.5 JSON is highlighted just fine, but starting with 2.0.6 object keys are rendered like strings, hurting readability.

Maybe this has something to do with "json: bottom-up rewrite, massively improve string performance" being introduced in 2.0.6 ?

Attached is an example (MonokaiSublime).

![json-with-2 0 5](https://cloud.githubusercontent.com/assets/1381583/26154371/7b648968-3b0f-11e7-9ea2-30cabb5ce197.PNG)
![json-with-2 0 6](https://cloud.githubusercontent.com/assets/1381583/26154372/7b6dc9c4-3b0f-11e7-8bb4-80ce502b20b2.PNG)

**Comment by jneen** [comment]
I decided that it's too much work for Rouge to do to validate JSON input, so I simplified the lexer. People want a lot of things out of the JSON lexer - the ability to highlight snippets of it, or add comments, highlight escapes within strings, etc. We used to have a very complicated lookahead regex on every string literal to determine that difference, and... it was just too expensive.

**Comment by sergionalin** [comment]
Uhm, while I can understand the performance cost and related troubles, still that's a pretty considerable impact for what should be a minor version (2.0.5 -> 2.0.6).
I mean, giving the scope of the change, introducing a new lexer when switching from 2.0 to 2.1 that would sound ok, but in a minor it seems a tad stretched.
My point of view, mind.

Anyway, since having object keys highlighted the same as string values is pretty bad for readability, how about introducing a flag? Want performance? Go fast and have all string highlighted the same. 
Want a more nuanced highlighting? Pay the performance price. Or something like that :)

**Comment by jneen** [comment]
We don't support that kind of flag, generally, unfortunately. I considered this a minor change, though I apologize for pushing it in a minor release. (though, frankly, the difference between minor and major releases is a bit academic for rouge since we don't have the resources to support backporting)

**Comment by jneen** [comment]
If you have an idea of a more performant way to make this distinction in the lexer, I would be happy to look at a pull request.

**Comment by domoritz** [comment]
Pygments still has a different class for keys and values in JSON objects: http://pygments.org/demo/6653499/. I loved Rogue as a drop in replacement for Pygments and Github pages now only supports Rogue. Unfortunately, now I have no way of differentiating keys and values in my syntax highlighting theme anymore.

**Comment by qB0t** [comment]
I'd say it totally ruined the whole thing! What's the point of marking up a code if there's no difference between a key and a value?.. Is there any way I can get it back?

**Comment by tomjoht** [comment]
Just chiming in here. I'm also struggling with this issue. I want our JSON code syntax highlighting to be more colorful. I echo the other sentiments shared here.
