### ISSUE TITLE
Php highlighting doesnt work without <?php

### ISSUE THREAD

**Issue by disharmonized** [jneen/rouge#676]
I cam here from GItlab:
https://gitlab.com/gitlab-org/gitlab-ce/issues/27208#note_30077666

## Summary

When i want to paste php code i had to add unnecessary <?php to make highlighting work.

![](https://gitlab.com/gitlab-org/gitlab-ce/uploads/4a6320785d652b86b6dc61ad87a1da24/image.png)

## Expected behavior

Highlighting in first example working.  

## Actual behavior

Highlighting in first example not working.

**Comment by BigChief45** [comment]
Well, seems about right ?

**Comment by disharmonized** [comment]
No, because if you want to paste part of code no need to begin it with  `<?php`. Besides you already told rogue, what language you want to paste via \`\`\`php

**Comment by kAworu** [comment]
IMHO it is correct *and* annoying. Maybe the PHP lexer should be able to handle two "languages" like `php` (continue with the current behaviour) and `php-inline` or something like that.

**Comment by jneen** [comment]
There is an option, `php?start_inline=1`. But in the next release we're implementing a feature that guesses whether you're starting inline or not - which can always be overridden with that option if it's wrong.

**Comment by jneen** [comment]
So it turns out `start_inline` and all other lexer options are broken in gitlab comments since https://gitlab.com/gitlab-org/gitlab-ce/commit/038d6febedc03280bd686d929057c02d05f2afd6. Closing this in favor of https://gitlab.com/gitlab-org/gitlab-ce/issues/21544.
