### ISSUE TITLE
Rouge should have more committers

### ISSUE THREAD

**Issue by gfx** [jneen/rouge#680]
It seems that the owner @jneen has no time to maintain rouge.

Rouge becomes really important gem today, so it has more committers.

**Comment by gfx** [comment]
I am one of the committers of https://github.com/tmm1/pygments.rb, but I have migrated the highlighter from pygments.rb to rouge in my projects.

So I'd like to maintain rouge when @jneen has a full schedule.

**Comment by BigChief45** [comment]
I agree. I've been wanting to do some pull requests, but the lack of maintenance isn't very motivating.

More maintainers are very needed.

**Comment by kAworu** [comment]
Yes please, there are many PR to merge (starting with 670 that is a month old).

**Comment by jneen** [comment]
I have just added @gfx and @dblessing as collaborators - hopefully we'll be able to keep up better now :]

**Comment by gfx** [comment]
Thank you. I hope rouge gets more progress ✌️
