### ISSUE TITLE
Dotfiles/Custom Syntax

### ISSUE THREAD

**Issue by mike3run** [jneen/rouge#681]
Hey there I'm looking to use [this color scheme](https://github.com/wbinnssmith/base16-oceanic-next/blob/master/rouge/base16-oceanicnext.rb) with rougify since it matches my terminal colors but I'm not sure if there's a way do it cleanly without messing with the source code here. Is there any secret option to import styles or something similar?

**Comment by jneen** [comment]
For the time being, i'd suggest:

```
ruby -r "/path/to/theme.rb" -- "$(which rougify)" highlight
```

**Comment by jneen** [comment]
The next release will add an `-r` flag to the highlighting mode.

**Comment by mike3run** [comment]
Thanks a lot for the answer! 😄

**Comment by mike3run** [comment]
hey @jneen i see there's a new release but I can't figure out how to use the new `-r` mode with it would you happen to have a quick example?

I really appreciate the work you've put in here i love using this

![screen shot 2017-06-19 at 21 47 05](https://user-images.githubusercontent.com/7088511/27314350-dddea4c8-5538-11e7-93d9-414a4aebae5d.png)

That's how I use it with FZF in vim to quickly preview things <3

**Comment by shelldandy** [comment]
Nowadays I'm using `highlight` which looks nicer inside fzf-vim with this setting on my vimrc

```.vimrc
let g:fzf_files_options =
    \ '--color "border:#6699cc,info:#fabd2f" --preview "highlight -O ansi --force {} 2> /dev/null"'
```
