### ISSUE TITLE
rougify command raises ArgumentError: unsupported signal SIGPIPE on Windows 10

### ISSUE THREAD

**Issue by BTx123** [jneen/rouge#688]
After trying to run the comand `rougify`, I receive this error:
```
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/rouge-2.0.7/bin/rougify:8:in `trap': unsupported signal SIGPIPE (ArgumentError)
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/rouge-2.0.7/bin/rougify:8:in `<top (required)>'
        from C:/tools/ruby24/bin/rougify:22:in `load'
        from C:/tools/ruby24/bin/rougify:22:in `<main>'
```
It fails with all other commands that use `rougify` as well.
For now, I have commented out `Signal.trap('SIGPIPE', 'SYSTEM_DEFAULT')` and `rougify` seems to work, but I don't know if this is okay for Linux machines ([attached rougify.txt](https://github.com/jneen/rouge/files/1057216/rougify.txt)).

**Comment by BTx123** [comment]
Related issues, working on fix:
https://github.com/defunkt/gist/pull/210
https://bugzilla.redhat.com/show_bug.cgi?id=965923

**Comment by jneen** [comment]
cc @maverickwoo could you look at this? I believe this was introduced in #549

**Comment by maverickwoo** [comment]
Oops, my bad! I will make a patch for this, test it on Windows (and macOS and Linux), and submit a new PR.
