### ISSUE TITLE
bash code like $'\0' breaks syntax highlighting

### ISSUE THREAD

**Issue by selivan** [jneen/rouge#698]
### Steps to reproduce

Public a page where bash code block contains `$'\0'`(bash-specific way to use string with escaped unprintable characters):

    ```bash
    null=$'\0';
    echo all further code is highlighted as string
    ```
### Expected result

See correct highlighting: `$'\0'` is string, characters after closing `'` are not.

### Actual result

All further code is displayed as string until parser stumbles upon single quote `'` character.

### Additional information

Live site on github pages with this problem: [selivan.github.io - ansible-check-on-commit-vault-files-are-encrypted](https://selivan.github.io/2017/04/08/ansible-check-on-commit-vault-files-are-encrypted.html).

First I contacted github-pages guys about this issue: https://github.com/github/pages-gem/issues/436, they sent me to upstream.

**Comment by jneen** [comment]
Can you see if you can reproduce this using master? I think the github-pages folks might be on a super-ancient version.
![2017-06-13 jun 06 1497389727_555x164](https://user-images.githubusercontent.com/225017/27105774-afe854da-5045-11e7-8c1c-689652c6f32a.png)

**Comment by selivan** [comment]
@jneen yep, it's not reproduced with 2.1.0 version, ancient bug it is.

You mentioned(https://github.com/jekyll/jekyll/pull/5919#issuecomment-308256914), that you are getting a lot of issues for rouge 1.x. I suppose you can add an issue template(https://help.github.com/articles/creating-an-issue-template-for-your-repository/) to this repository, mentioning that. So jekyll users will stop bothering you and will start bothering jekyll guys to update to supported rouge version.

**Comment by jneen** [comment]
Haha yep, that would be helpful. I do hope they update soon!
