### ISSUE TITLE
tabwidth

### ISSUE THREAD

**Issue by ukos-git** [jneen/rouge#707]
I was wondering if there was a way to set the tabwidth to 4 spaces within a template.

**Comment by jneen** [comment]
Not sure what you mean - Rouge doesn't have a concept of templates. If you're using hard tabs and want to change the size they're displayed in HTML, you might look at https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

**Comment by ukos-git** [comment]
ok. The CSS property was exactly what I was searching for.

I have now added a pre style definition in front of my html output and now a tab is displayed as 4 spaces.
```html
<html>
<head><style type="text/css"> 
pre { tab-size: 4; /* Set tab size to 4 spaces */  }
-->input css
</style></head>
<body>
-->input html
</body>
</html
```
It would be quite nice to mimick the 4-spaces behaviour of the standard editor by default within the theme. Some comments etc are aligned to fit to this tabwidth.

I'm using rouge to generate the style file like this:
```bash
rouge/bin/rougify style igorpro
```
Is it possible to generate the tab-size statement `pre { tab-size: 4;}` somehow automatically at the start of the css definition within `lib/rouge/themes/igor_pro.rb`? This input then probably must only affect css styles.

**Comment by dblessing** [comment]
This is outside the scope of Rouge. `tab-size` should not be output using `rougify style` IMO. Can you implement it 'manually' in your HTML head like you've done in the example above? That should work just fine. If I'm misunderstanding, please let me know.

**Comment by ukos-git** [comment]
You're right. It can be done manually.
I was just thinking that maybe there exists a way to tell github in the end that code highlihgting should be done with 4 spaces = 1 tab. 

Closing this issue is just fine because it has no significant relevance to code highlighting itself.
