### ISSUE TITLE
Support for HashiCorp Configuration Language (HCL)

### ISSUE THREAD

**Issue by cavaliercoder** [jneen/rouge#722]
Thanks for this great library! It makes my Jekyll site look so much better than plain text.

Please consider adding support for HCL, the language used by HashiCorp tools like Terraform. This would mean that Terraform examples on my site and other could be more beautifully highlighted.

HCL spec: https://github.com/hashicorp/hcl

**Comment by DanielMarquard** [comment]
+1. We'd love to see this in GitLab.

**Comment by jacob-carlborg** [comment]
Here's the Terraform grammar for TextMate for reference [1].

[1] https://github.com/aurynn/Terraform.tmbundle/blob/master/Syntaxes/Terraform.tmLanguage

**Comment by cavaliercoder** [comment]
Thank you! Very cool.
