### ISSUE TITLE
Syntax error prevents the page to be rendered.

### ISSUE THREAD

**Issue by vahid-dan** [jneen/rouge#768]
Hi;

I was wondering if there is any way to use Rouge syntax highlighting on a Jekyll website and make it ignore the syntax errors. Currently, if there is a syntax error, Jekyll throws an error and prevents the page to be rendered.

Thanks,
Vahid

**Comment by jneen** [comment]
That's... definitely wrong behavior. Rouge should yield an `Error` token, which is highlighted red. Can you give an example of the kind of syntax error that causes this problem?

**Comment by vahid-dan** [comment]
@jneen,

Thanks for your reply.

I have a Jekyll website and this is a partial `json` file in the documentations that causes this error: ```{ {3478, udp}, ejabberd_stun, [] },```.

And this is the error:

```
Liquid Exception: Liquid syntax error (line 91): Variable '{{3478, udp}' was not properly terminated with regexp: /\}\}/ in wiki/Deploying-XMPP-STUN-TURN-Services.md
...error:
             Error: Liquid syntax error (line 91): Variable '{{3478, udp}' was not properly terminated with regexp: /\}\}/
             Error: Run jekyll build --trace for more information.
```

I thought it is because of the syntax checker since the same document in GitHub wiki is being displayed as I expect.

Thanks,
Vahid

**Comment by jneen** [comment]
Haha, well that looks like it's a liquid syntax error, since it's interpreting `{{` as the start of a liquid block before even passing anything to rouge. I'm not sure how you escape those things in liquid.

**Comment by vahid-dan** [comment]
Jeanine,

Liquid support gave me a workaround which is not what I was looking for since my documents are being imported automatically from GitHub wiki to Jekyll website and I don't want to edit them manually:

> Liquid is confused by the curly braces, since they normally form Liquid tags.
> 
> To prevent an error, you'll need to wrap the JSON in Liquid raw tags, like this:
> ```
> {% raw %}
> { {3478, udp}, ejabberd_stun, [] },
> {% endraw %}
> ```

Thanks again for your time. :-)

Cheers,
Vahid
