### ISSUE TITLE
CRLF line endings are scanned wrong in python (and probably break other things too!)

### ISSUE THREAD

**Issue by talhasaruhan** [jneen/rouge#772]
Comments starting with hash character "#" print out a new line after the comment itself. Plus this breaks line number and code alignment.

Edit: Changing the language to C etc. fixes the problem. When I look at source code it's identical, except for the classes of each word, which obviously colors the word. I did try changing span class in developer tools, but as expected, it only changed colors. 

Edit 2: OK, There's a new line character right after the closing span tag of comment line. Tried "escaping" the hash character, but couldn't get it to work.

**Comment by jneen** [comment]
Wow, that sounds defintely like wrong behavior. Could you paste the code snippet and the HTML output? Also, which formatter you're using? You could also try pasting a sample into rouge.jneen.net.

**Comment by talhasaruhan** [comment]
OK, this just got weirder. I got intended results when I simply copied the code below to another page. But the other page still displays them incorrectly.
Code:

```
{% highlight python linenos %}
# comment
for i in range(5):
	print(5)
{% endhighlight %}

```python
# comment
for i in range(5):
	print(5)
```

{% highlight c %}
# comment
for i in range(5):
  print(5)
{% endhighlight %}
```
![screenshot from 2017-09-12 00-55-50](https://user-images.githubusercontent.com/15991519/30298731-2daef9e0-9755-11e7-982f-f5541c6dda0a.png)
![screenshot from 2017-09-12 00-56-05](https://user-images.githubusercontent.com/15991519/30298732-2f9df3fa-9755-11e7-86e2-23ae149dbacf.png)

**Comment by talhasaruhan** [comment]
OK, I am 100% positive this has something to do with file encoding or line break incompatibility. After I create a new file any copy the contents over, it seems to work fine. Once I got the time, I can figure out the exact reason.

**Comment by jneen** [comment]
Okay! Next is, what does rouge output when given CRLF endings?

```
$ rougify -f html file-with-crlf-endings.py
```

**Comment by talhasaruhan** [comment]
Yeah, exact same thing, there's a new line after the closing span tag of comment line.

**Comment by jneen** [comment]
Okay, I've updated the title, maybe @gfx or @dblessing will have a chance to take a look soon.

**Comment by jneen** [comment]
In the meanwhile, you can run your input through `string.encode(universal_newline: true)` before passing it to rouge, if you have that level of control.

**Comment by talhasaruhan** [comment]
Thanks, I'm already on local, so I just ran a bash script to fix all the files for me. Hope this helps someone else.

**Comment by jneen** [comment]
It's possible this is simply a documentation fix - asking users to convert their newlines before passing strings to rouge. Or, we could try to automatically convert.

**Comment by gfx** [comment]
IMO Rouge should normalize its input source for newlines and BOM.

cf. https://github.com/jneen/rouge/issues/767

**Comment by gfx** [comment]
note: `File.read("foo.txt", mode: "rt:bom|utf-8")` to remove BOM and normalize newlines.

**Comment by jneen** [comment]
That works if the input is a file, but more often the file is read elsewhere and passed to rouge as a string.
