### ISSUE TITLE
SCSS breaks on `&[attr^="value"]` selector

### ISSUE THREAD

**Issue by AlexWayfer** [jneen/rouge#805]
:pensive: 

![image](https://user-images.githubusercontent.com/6510020/31502516-ff5b792c-af75-11e7-8ff4-2b3552b91bcb.png)

http://rouge.jneen.net/pastes/GKa7

**Comment by hibariya** [comment]
The same thing happens on Sass. The causes of these problems might be relevant.
http://rouge.jneen.net/pastes/A32x

**Comment by AlexWayfer** [comment]
Thank you, @hibariya!
