### ISSUE TITLE
[INVALID] Colouring in Pale Moon

### ISSUE THREAD

**Issue by sergeevabc** [jneen/rouge#825]
Pale Moon 27.6 (a fork of Firefox ESR 38) x64.

Put cursor into selectbox with colour schemes on [demo website][1] and press UP or DOWN.
Colouring in the right box should change appropriately, but it does not happen.
Could you be so kind to fix it?

[1]: http://rouge.jneen.net/

**Comment by jneen** [comment]
Hi @sergeevabc, thanks for opening this. Could you open this on http://github.com/jneen/rouge.jneen.net instead? That's for the website, this is for the rouge project itself. Thanks!
