### ISSUE TITLE
Swift lexer not matching type names

### ISSUE THREAD

**Issue by johnfairh** [jneen/rouge#861]
In latest rouge some Swift identifiers aren't matched properly.  Eg. from the swift visual test, including type names in constructors:
![screen shot 2018-01-11 at 11 25 20](https://user-images.githubusercontent.com/26768470/34823463-5269732e-f6c2-11e7-85c4-4c1f17daf322.png) should be (3.0.0):
![screen shot 2018-01-11 at 11 22 37](https://user-images.githubusercontent.com/26768470/34823334-eaa0d07a-f6c1-11e7-8ce3-20c470573d7b.png)
...type names in function return position:
![screen shot 2018-01-11 at 11 25 33](https://user-images.githubusercontent.com/26768470/34823434-3b59538e-f6c2-11e7-80b0-330dbe50d5e0.png) should be (3.0.0): 
![screen shot 2018-01-11 at 11 21 54](https://user-images.githubusercontent.com/26768470/34823325-e0f6e578-f6c1-11e7-932f-2930789bd996.png)
...some keywords:
![screen shot 2018-01-11 at 11 24 55](https://user-images.githubusercontent.com/26768470/34823485-69b512e0-f6c2-11e7-816c-7d5279b4c99e.png) should be (3.0.0):
![screen shot 2018-01-11 at 11 22 58](https://user-images.githubusercontent.com/26768470/34823340-efe68c1e-f6c1-11e7-9d0b-a23d4558f84d.png)

@dan-zheng I think it's f8eb15cceba2811b4a351ff418538a880a5ac6bd from #837 doing this, can you see a way to fix it without reverting?

**Comment by dan-zheng** [comment]
Thanks @johnfairh, good eye! I just submitted a PR patching these bugs.

**Comment by dan-zheng** [comment]
The PR is done: @johnfairh could you please review? Much appreciated!

**Comment by johnfairh** [comment]
Fixed in 3.1.1 🎉
