### ISSUE TITLE
Why is the library `load`-ing resources instead of `require`-ing them?

### ISSUE THREAD

**Issue by ashmaroli** [jneen/rouge#886]
Tracing the causes for String allocations in a Jekyll Site led me to `rouge.rb` which `load`-s the required files.

While I tried to look for the reason as to why this approach was opted for instead of the more-optimal `require` or `require_relative`, I could only find traces of info (revolving around the lexers) in the `git logs`..

Its possible that Jekyll or any other consumers downstream can benefit from the reduced String allocations from switching over to `require` calls (and immutable strings using the `frozen_string_literal: true` comment., but that's a different issue altogether.)

**Comment by lammar2315** [comment]
Trying to release assets

**Comment by dblessing** [comment]
Great question. I'm not sure. Are you able to do some testing with Rouge and see if everything still works with such a change?

**Comment by ashmaroli** [comment]
I haven't tried testing with that change. Thought I'd seek out the rationale first.. :slightly_smiling_face:

**Comment by dblessing** [comment]
I don't know why it was written that way. I think @jneen would have to answer that. I'm not sure we'll hear from her as she's busy with other things at the moment.

**Comment by jneen** [comment]
`load` means the library is reloadable in testing, which is really important for the lexer development flow. is it causing problems?

**Comment by ashmaroli** [comment]
> is it causing problems?

Not really. But was curious to know why this approach was opted for..

**Comment by jneen** [comment]
In that case I would prefer it be left as-is, since the current approach enables `Rouge.reload`.

**Comment by ashmaroli** [comment]
fair enough.
