### ISSUE TITLE
R highlighting: some function names coloured, not others

### ISSUE THREAD

**Issue by stragu** [jneen/rouge#925]
For some reason, `dim` gets highlighted in `dim()` but not other function names.

Example: http://rouge.jneen.net/pastes/7Gl4

Side question: any reason why argument names and comments don't get rendered differently?

**Comment by itcarroll** [comment]
Primitive functions are special ([L27](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge/lexers/r.rb#L27)).

```r
> is.primitive(dim)
[1] TRUE
> is.primitive(str)
[1] FALSE
```

**Comment by stragu** [comment]
OK, no problem! Thanks for the explanation :)
