### ISSUE TITLE
Ruby highlighting seems broken.

### ISSUE THREAD

**Issue by Erquint** [jneen/rouge#928]
Can we have actual Ruby highlighting?

This is actual highlighting:
![Screeenshot](https://i.imgur.com/1rDXjB6.png)

This is not actual highlighting:
![Screeenshot](https://i.imgur.com/phoEhxA.png)
Coloring everything yellow is not how highlighting is supposed to work.
I'm guessing this is GitHub's bug.

This isn't much better though.
![Screeenshot](https://i.imgur.com/AtV8gs5.png)

**Comment by jneen** [comment]
Please don't leave comments like this on open source projects in the future.

The issue seems to be with the theme that you are currently using. Are these GitLab screenshots? I suggest you reach out to them.

**Comment by Erquint** [comment]
First screenshot is of Sublime Text just for example of good highlighting.
The rest two are from GitHub.
[This page](https://help.github.com/articles/using-syntax-highlighting-on-github-pages/) lead me to believe it uses it. The wording there is just as ambiguous as on [this page](https://help.github.com/articles/about-repository-languages/).
I'm just trying to figure out why Ruby highlighting is so atrocious on GitHub.

**Comment by Erquint** [comment]
Thanks for clarifying what you could though.
Have a nice day.
