### ISSUE TITLE
Syntax Vue.js: Problem with "Unexpected character $ (dollar sign)"

### ISSUE THREAD

**Issue by alxmcr** [jneen/rouge#971]
Hi, Rouge's team:

I'm starting a personal blog with **Jekyll** and create some posts, but when I use the **Vue.js syntax**, I have a problem with the process of generating the files. It isn't completely successful. I have this warning: 

```
Liquid Warning: Liquid syntax error (line 6): Unexpected character $ in "{{ $route.params.id }}"
```

### How Can you reproduce this problem?

1. Create a new Jekyll project (Source: [Quick-start Instructions](https://jekyllrb.com/)) 
```
$ gem install bundler jekyll
$ jekyll new my-awesome-site
$ cd my-awesome-site
$ bundle exec jekyll serve
# => Now browse to http://localhost:4000
````

2. Install the `kramdown` and `rouge` gems
```
$ gem install kramdown rouge 
```
3. Update `_config.yml`

```
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
```

4. Create a New post Markdown (For example: `2018-08-14-vue-syntax.md`)
5. Copy these lines ([Gist](https://gist.github.com/alxmcr/4c87feab0d3f1edb4c8dc2f5bb2ab310) ):

![image](https://user-images.githubusercontent.com/8689897/44104850-ed772718-9fbd-11e8-91cc-d516570d9a79.png)

6.  Open the terminal

```
$ cd my-awesome-site
$ bundle exec jekyll serve
# => Now browse to http://localhost:4000
````

Unfortunately, you have this terminal output:

![image](https://user-images.githubusercontent.com/8689897/44105251-1afbf280-9fbf-11e8-8056-bfe478d85940.png)

And If you open your browser, you watch it:

![image](https://user-images.githubusercontent.com/8689897/44105348-6a32e714-9fbf-11e8-9008-b57e6205eb58.png)

How can I solve this problem? Can you help me, please? I'll appreciate it.

**Comment by dblessing** [comment]
This looks like a problem with Liquid, not Rouge. Liquid is interpreting
the ‘{{ ... }}’ as something it should interpolate. I don’t know how to
tell it not to try to interpolate inside code fences. At any rate, I don’t
think this is a Rouge problem.

**Comment by alxmcr** [comment]
Thanks, @dblessing for answering!

Well, I was researching more on the Internet, I found this article [Jekyll: Code snippet highlighting](https://jekyllrb.com/docs/templates/#code-snippet-highlighting) and I did some changes in my file ([Gist - Button 'raw'](https://gist.github.com/alxmcr/d6846f8b70e077c1c84dcd63b2821d65)):

![image](https://user-images.githubusercontent.com/8689897/44110863-e1483f3e-9fce-11e8-9c3a-37b8b3bfaa5f.png)

I used `{% raw %}` and  `{% endraw %}` and the error in the Terminal *disappeared* 😀.

![image](https://user-images.githubusercontent.com/8689897/44110659-484185ac-9fce-11e8-8ad3-1583d7c496c6.png)

But, I went to my Browser and this was the result:

![image](https://user-images.githubusercontent.com/8689897/44110739-861242f4-9fce-11e8-8fb2-e1022c46f89d.png)

The content is **empty** 🙁.

**Can you help me, Please? 
You think, Should I write this issue in [Liquid's repository](https://github.com/Shopify/liquid) ?**

**Comment by dblessing** [comment]
> You think, Should I write this issue in Liquid's repository ?

Yes, sorry. I'm not very familiar with Liquid but it appears to be an issue there rather than Rouge.
