### ISSUE TITLE
Puppet syntax broken in a number of contexts

### ISSUE THREAD

**Issue by alexharv074** [jneen/rouge#979]
I am using the Rouge gem in my Jekyll on Github blog and have found a number of issues with the Puppet syntax highlighter.

(I can see from the revision history that it hasn't really been changed since 2013, so at least some of the problems would be that it lacks Puppet >= 4 syntax support.)

Issue 1 (note the red equals sign), example 1:

<img width="555" alt="screen shot 2018-09-03 at 9 48 07 pm" src="https://user-images.githubusercontent.com/2305330/44985274-1627f100-afc3-11e8-9606-be8f09d88ae6.png">

Issue 1, example 2:

<img width="287" alt="screen shot 2018-09-03 at 9 52 41 pm" src="https://user-images.githubusercontent.com/2305330/44985440-be3dba00-afc3-11e8-93ad-3632c7fb72d5.png">

Issue 2:

<img width="505" alt="screen shot 2018-09-03 at 9 50 27 pm" src="https://user-images.githubusercontent.com/2305330/44985335-6901a880-afc3-11e8-8d93-be5457a8ed6b.png">

These are from two posts online [here](https://alexharv074.github.io/2017/05/31/using-create_specs-to-refactor-puppet.html) and [here](https://alexharv074.github.io/2018/09/02/pretty-printing-puppet-data.html).

**Comment by alexharv074** [comment]
Geoff Williams wrote in the Puppet Community Slack:

> @alex Just had a quick look at that library. Seems that the lexer for puppet goes to `rule /[$]#{qualname}/, Name::Variable`, I tried to find the definition of `Name::Variable` and closest I got was https://github.com/sinatra/mustermann/blob/master/mustermann/lib/mustermann/ast/compiler.rb I'd guess `Name::Variable` doesn't match Puppet's idea of a regex, although the library does seem to support hashes. What if you try assigning a hash with only one level, or an array, or just a simple variable? Could be that the regex used just doesn't support n-level nesting?

**Comment by alexharv074** [comment]
@jneen if you could give me a clue what might be wrong I'd be happy to try to work on a fix. I did have a look but I can't get my head around the code. E.g. where does `Name::Variable` get defined?

**Comment by dblessing** [comment]
Hi @alex. You don’t need to worry about the definition of `Name::Variable‘.
It’s a token that Rouge uses only to color items later on. You will need to
adjust rules in the lexer (add, remove, rearrange) to fix the problem.

Wiki has some instructions on debugging/testing lexers
https://github.com/jneen/rouge/wiki/Setting-up-Ruby. Let me know if you
have more questions and I can point you in the right direction.

**Comment by jneen** [comment]
If you're curious where it's defined, it's in `lib/rouge/token.rb`. But as @dblessing already mentioned, it's nothing more than a fancy symbol - the type of tokens that are variables.

You can try running

``` bash
rougify -L debug=1 -f null my_file.pp
```

to get a debug trace of the lex. (`-L debug=1` sets debugging on, and `-f null` uses the "null" formatter, which suppresses normal output.)

**Comment by alexharv074** [comment]
Weirdly enough the lexer simply wasn't recognising the `=` sign as an Operator. Fixed:

Example 1
<img width="444" alt="screen shot 2018-09-04 at 7 59 44 pm" src="https://user-images.githubusercontent.com/2305330/45025483-f3f3a900-b07e-11e8-86a8-370ed674176f.png">

Example 2
<img width="227" alt="screen shot 2018-09-04 at 8 00 22 pm" src="https://user-images.githubusercontent.com/2305330/45025494-fb1ab700-b07e-11e8-870b-6755299e3539.png">

Example 3
<img width="341" alt="screen shot 2018-09-04 at 8 00 53 pm" src="https://user-images.githubusercontent.com/2305330/45025505-feae3e00-b07e-11e8-950c-54c1479c8cb1.png">

**Comment by alexharv074** [comment]
@jneen I raised a PR to fix it above. How long will it take for the fix to propagate to Jekyll on Github?

**Comment by dblessing** [comment]
Thanks for the PR! I’ll review today and get it merged. It will be in the
next release which I hope to publish in the coming weeks.
