### ISSUE TITLE
GraphQL multiline strings

### ISSUE THREAD

**Issue by langpavel** [jneen/rouge#992]
Looks like multiline strings are not supported.
They are often used for descriptions. In this case highlighted code is much worse readable than plain text

for example code like this:

```graphql
"""
Decimal number serialized as string.

Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`

Format:
  `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?

Example:
 - `"1000"`
 - `"0.00000001"`
 - `"-10"`
 - `"+1"`

This is invalid:
 - `".01"` *missing preceding zero*
 - `"1,000.00"` *invalid character*
 - `"1e-10"` *exponential form is not allowed*
"""
scalar Decimal

```

**Comment by dblessing** [comment]
@langpavel Is the above example exactly valid as written? Or can the strings only be present as a value for something?
