### ISSUE TITLE
GraphQL: Markdown descriptions

### ISSUE THREAD

**Issue by langpavel** [jneen/rouge#993]
This depends on #992 

But question is if inline descriptions can be Markdown hiqhlighted, for exampl same code as in #992:

```graphql
"""
Decimal number serialized as string.

Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`

Format:
  `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?

Example:
 - `"1000"`
 - `"0.00000001"`
 - `"-10"`
 - `"+1"`

This is invalid:
 - `".01"` *missing preceding zero*
 - `"1,000.00"` *invalid character*
 - `"1e-10"` *exponential form is not allowed*
"""
scalar Decimal
```

may be rendered similar to this:

```graphql
"""
```
> ### Decimal number serialized as string.
> 
> Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`
> 
> Format:
>   `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?
> 
> Example:
>  - `"1000"`
>  - `"0.00000001"`
>  - `"-10"`
>  - `"+1"`
> 
> This is invalid:
>  - `".01"` *missing preceding zero*
>  - `"1,000.00"` *invalid character*
>  - `"1e-10"` *exponential form is not allowed*
```graphql
"""
scalar Decimal
```

**Comment by dblessing** [comment]
Is there a spec in GraphQL for this? Should multiline strings like this, that aren't a value for something, always be interpreted as markdown?

BTW, #586 makes more sense after seeing this. I'd like to know more about this, though, before figuring out how to handle it.

**Comment by dblessing** [comment]
I found the spec at https://facebook.github.io/graphql/draft/#sec-Descriptions. Perfect!
